### ISSUE TITLE
MinimalOpenApiExample - add Swagger JSON endpoints doesn't work on production

### ISSUE THREAD

**Issue by Gerappa92** [dotnet/aspnet-api-versioning#1007]
I encountered an issue with Swagger when deploying my application from the local environment to production. Initially, everything was working fine locally. However, after deployment, I noticed the following error message being displayed in the Swagger interface:

> Fetch error Not Found /swagger/v1/swagger.json

In the local environment, the Swagger route was accessed using the following URL:
`https://localhost:7080/swagger/index.html`

In the production environment, the application's host had an additional route:
`http://my-awesome-page.com/route-to-my-application/swagger/index.html`

Unfortunately, Swagger was trying to retrieve the JSON file from the wrong URL. 
The additional rout was skipped:
`http://my-awesome-page.com/swagger/v1/swagger.json`

I found that the issue lies in the wrong adding Swagger JSON endpoint:

https://github.com/dotnet/aspnet-api-versioning/blob/f29831ea21d69d44dba1e1b2916da6a3d93514c6/examples/AspNetCore/WebApi/MinimalOpenApiExample/Program.cs#L275

To resolve this issue, I made the following change to the URL variable:
`var url = $"{description.GroupName}/swagger.json";`

After making this modification, Swagger started working correctly in both the local and production environments.

**Comment by commonsensesoftware** [comment]
The examples are just that - _examples_. They are meant to show how to put all the pieces together and not necessarily deploy a production-ready application. While I do make an effort to have the samples be as close to a real application as possible, there are nearly infinite variations that someone might use. It looks like you might be using a proxy in production. Did you enable `app.UsePathBase("/route-to-my-application")` for the production environment?

The default Swashbuckle route template is `/swagger/{documentName}/swagger.json`. This is called out in the [Swashbuckle documentation](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#change-the-path-for-swagger-json-endpoints) as well as the [Microsoft documentation](https://learn.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle). I'm inclined to use the default configuration for simplicity. The examples are only meant to show the bare minimum of Swashbuckle configuration to connect the pieces. They are not meant to show how to use Swashbuckle or perform advanced configuration. There are many other examples and documentation pages to cover that.

The examples are in a runnable state. If you're able to demonstrate that is somehow not true, I'm happy to look into addressing that. The issue you have outlined seems very specific to your particular application and requirements.

**Comment by Gerappa92** [comment]
Before adding the Versioning library I used the default builder `app.UseSwaggerUI();` without any options.

Regarding the example we are using options to add Swagger JSON endpoints in the following way:

https://github.com/dotnet/aspnet-api-versioning/blob/main/examples/AspNetCore/WebApi/MinimalOpenApiExample/Program.cs#L267-L279
```
app.UseSwaggerUI(
    options =>
    {
        var descriptions = app.DescribeApiVersions();

        // build a swagger endpoint for each discovered API version
        foreach ( var description in descriptions )
        {
            var url = $"/swagger/{description.GroupName}/swagger.json";
            var name = description.GroupName.ToUpperInvariant();
            options.SwaggerEndpoint( url, name );
        }
    } );
```

But when you look under the hood what is happening in the default `app.UseSwaggerUI();` you will see that there is no `swagger` in the URL:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIBuilderExtensions.cs#L41

`options.ConfigObject.Urls = new[] { new UrlDescriptor { Name = $"{hostingEnv.ApplicationName} v1", Url = "v1/swagger.json" } };`

I fully understand that this is an example, but why not make it more robust? I believe, these examples are great and are worth 100 more than any documentation.

**Comment by commonsensesoftware** [comment]
I think we may have our wires cross ever so slightly. There are two different route templates. The default route template for the Swashbuckle middleware the serves OpenAPI documents most definitely has the `/swagger` prefix as seen here:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/8f363f7359cb1cb8fa5de5195ec6d97aefaa16b3/src/Swashbuckle.AspNetCore.Swagger/SwaggerOptions.cs#L19

The URL passed to `SwaggerUIOptions.SwaggerEndpoint` must match this template. The UI doesn't know about or discover the OpenAPI documents, so this is how the connection between the two is made and the dropdown is populated. Interestingly enough, things work with or without the prefix.

| Route Template | Works |
| ----------------- | ------- |
| `/swagger/{description.GroupName}/swagger.json` | Yes |
| `/{description.GroupName}/swagger.json` | Yes |
| `swagger/{description.GroupName}/swagger.json` | No |
| `{description.GroupName}/swagger.json` | No |
| `./swagger/{description.GroupName}/swagger.json` | No |

This appears to be because `SwaggerUIOptions.RoutePrefix` has a default value of `"swagger"`:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/8f363f7359cb1cb8fa5de5195ec6d97aefaa16b3/src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIOptions.cs#L15

If you change the configuration like this:

```c#
var url = $"/{description.GroupName}/swagger.json";
var name = description.GroupName.ToUpperInvariant();
options.SwaggerEndpoint( url, name );
options.RoutePrefix = string.Empty;
```

Things break. Similarly, navigate to the document at `<host>/v1/swagger.json` and you'll get 404. The document is still at `<host>/swagger/v1/swagger.json`. There appears to be a loose, implicit connection between the SwaggerUI route prefix and the OpenAPI document files.

As noted above, the Microsoft documentation calls out the following paragraph:

>If using directories with IIS or a reverse proxy, set the Swagger endpoint to a relative path using the `./` prefix. For example, `./swagger/v1/swagger.json`. Using `/swagger/v1/swagger.json` instructs the app to look for the JSON file at the true root of the URL (plus the route prefix, if used). For example, use `https://localhost:<port>/<route_prefix>/swagger/v1/swagger.json` instead of `https://localhost:<port>/<virtual_directory>/<route_prefix>/swagger/v1/swagger.json`.

You didn't mention how you were hosting, but that seems to reflect the behavior you are seeing.

The variances in hosting have been problematic over the years. They are close, but not all the same. I used to use IIS Express quite a bit, but that too can be a pain. I've moved to a self hosting for all examples and platforms to make things as consistent as possible.

If you are using IIS or a reverse proxy, then the correct course of action here appears to be a big comment in the code about these particular gotchas. I have no problem with that. The examples will run without issue _as is_, but if you try to rehost it another way, it may not. On one hand, I think that should be potentially expected. If there is a way to make one of the default configurations work for all, I support it. I tried using `./` as the prefix, but that doesn't work for self hosting. It's a bit curious that removing the prefix works for you in another environment, even though the OpenAPI documents ultimately have the same URL.

Removing the prefix, as you've suggested, _should_ still require a comment as to _why_ it deviates from the default. My observation is that there is a difference in the handling of the `/` and `./` prefix by different hosts.

**Comment by commonsensesoftware** [comment]
I appreciate the discussion and thought that went into this thread. While there is a loose connection, API Versioning is not about OpenAPI, Swagger, or Swashbuckle nor how it should be hosted from an application. I have carefully created examples based on the most vanilla of configurations to show the pieces working together. I do try to make a point of having the examples be similar to _real_ scenarios, which many examples don't do. The current setup has been that way for years (the original I believe) and - right or wrong - it matches the Swashbuckle and Microsoft documentation (as linked above). In reviewing this one last time, I'm inclined to leave it as is.

That being said, this issue will always be here for people to find and decide for themselves. If you think it's worth adding to the wiki documentation for Swashbuckle integration, I'm 100% onboard with that and happy to add something.

Beyond that. This thread has reached its conclusion. Thanks again for the health debate and advocating to make things better. 😉
