### ISSUE TITLE
Version constraint doesn't work

### ISSUE THREAD

**Issue by rosebyte** [dotnet/aspnet-api-versioning#1014]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I set a controller to a version, let's say 
```
[ApiVersion("1.0")]
[Route("api/v{version:apiVersion}/example")]
public class ExampleController : ControllerBase
```

And turn using a default version off:

```
services
        .AddApiVersioning(options => options.AssumeDefaultVersionWhenUnspecified = false)
        .AddMvc();
```

I can call endpoints from the controller using the correct path `~/api/v1/example/resource`, however, I can use any other version and I get through, for example `~/api/v22/example/resource`.

### Expected Behavior

I expect paths with unsupported versions to be filtered and returning 404.

### .NET Version

7.0.203

**Comment by commonsensesoftware** [comment]
From your example, it doesn't look like this controller has _API Behaviors_ applied. Controllers are expected to have `[ApiController]` applied so that they can be disambiguated from non-API controllers. It's possible that you've indicated that all controllers are API controllers by targeting the assembly (e.g. `[assembly: ApiController]`), but I don't have enough information.

Filtering controllers that have `[ApiController]` is just a convention. This is facilitated by the `IApiControllerFilter` service. The default implementation simply includes a sequence of `IApiControllerSpecification` instances. The entire service can be replaced or you can add/replace new specifications. There is a provided default implementation if you want to map an implementation that performs no filtering.

Without the controller being identified as an API controller, no other API versioning behaviors or policies will be applied. The `ApiVersionRouteConstraint` only handles extracting and setting the requested API version from the request URL. This doesn't require other parts of API Versioning to work, which would result in any well-formed API version value to match. This appears to be the behavior that you are observing.

Setting `AssumeDefaultVersionWhenUnspecified = true` will **never** work when you version by URL segment _unless_ you use double-route registration and have a route template that does not include the API version constraint. In the same way, `/order/{id}/items` will never match with a default value for `{id}`. This is simply something that the routing system doesn't support. The configuration was **only** meant for backward compatibility, meaning you had `api/example` for V1 and now you need `api/v{version:apiVersion}/example` for V2+. If you are using this option for something else, then you are abusing what the feature was intended to do.
