### ISSUE TITLE
Problem with describing reponse codes in minimal api

### ISSUE THREAD

**Issue by msmolka** [dotnet/aspnet-api-versioning#1032]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

for controller actions I can use xdoc to describe response codes

``` xml
/// <response code="400">Something wrong happened</response>
```
I'm not able to find equivalent for minimal api metadata. The values should go to 

``` c#
operation.Responses[400].Description = "some description"
```

but where the metadata is set?

**Comment by commonsensesoftware** [comment]
Is this specific to API Versioning? This appears to be general in nature with respect to using OpenAPI in _Minimal APIs_. I recommend starting with the [OpenAPI Support in Minimal APIs](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/openapi). Pairing up XML Comments is a specific feature of Swashbuckle. I'm not sure if it supports that in _Minimal APIs_.  If you have specific questions about API Versioning withing these contexts, I'm happy to answer them.

**Comment by msmolka** [comment]
Probably not directly. I’ve seen example with WithOpenApi, but I know I cannot use it here. That’s why I’m asking.

sorry for bothering

**Comment by commonsensesoftware** [comment]
`WithOpenAPI` just attaches the `OpenApiOperation` as metadata. You should be able to configure the information directly or with one of the many specialized extension method (though I'm not sure there is one for this specific case).

As it relates to API Versioning, you can use all of the provided APIs, but you need to be careful if _interleave_ versions and you want OpenAPI support on a _Minimal API_. The current design only support attaching a single `OpenApiOperation`, which can produce the wrong results. I've gone through the scenario with the ASP.NET team, but it doesn't look like we will see that enhancement in .NET 8. The easiest way to avoid that problem is to have a single _Minimal API_ (action method) defined per route+version combination (e.g. do not interleave). Everything else should behave normally. If you're hitting a wall here, I can try to help out.

In terms of XML Comments, API Versioning doesn't get use them or involve them in any way.
