### ISSUE TITLE
AddVersionedApiExplorer not working in Asp.Versioning

### ISSUE THREAD

**Issue by julianalsemmani** [dotnet/aspnet-api-versioning#1061]
Hey, so I just switched to Asp.Versioning, but can't seem to get this working. Everything else works fine.

```cs
services.AddVersionedApiExplorer(options =>
{
    options.GroupNameFormat = "'v'VVV";
    options.SubstituteApiVersionInUrl = true;
});
```

Any solution for this one? Tried searching a bit round, but couldn't find anything specific.

**Comment by commonsensesoftware** [comment]
Is this for ASP.NET Core or ASP.NET Web API? It's hard to tell. It looks like it might be ASP.NET Core due to the `services` variable name, so I'll roll with that assumption.

Starting in `6.0`, all of the API Versioning features hang off of `IApiVersioningBuilder`. This centralizes configuration in a consistent way. The change is documented in the [migration guide](../wiki/Migration#configuration).

It's not clear if you only have _Minimal APIs_ or you also have controllers. Regardless, the configuration is nearly identical:

```c#
var builder = WebApplication.CreateBuilder( args );
var services = builder.Services;

services.AddApiVersioning()     // Core API Versioning services with support for Minimal APIs
        .AddMvc()               // API version-aware extensions for MVC Core with controllers (not full MVC)
        .AddApiExplorer()       // API version-aware API Explorer extensions
```

The API Explorer extensions are included in [Asp.Versioning.Mvc.ApiExplorer](https://www.nuget.org/packages/Asp.Versioning.Mvc.ApiExplorer). The old extension method was `AddVersionedApiExplorer` because it would have otherwise been ambiguous with the built-in `AddApiExplorer`. Now that the extension methods all hang off of `IApiVersioningBuilder`, the names can be more succinct and are unambiguous.

**Comment by julianalsemmani** [comment]
Sorry for not being more specific. It's for ASP.NET Core Web API.

**Comment by commonsensesoftware** [comment]
No worries. I figured as much. [ASP.NET Web API](https://learn.microsoft.com/en-us/aspnet/web-api/) runs on the ASP.NET (4.x) _Classic_ stack using the .NET Framework. You can, however, build a _web API_ on [ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/apis), which runs on .NET. They are both _ASP.NET_ and you can build _web APIs_ with them both. API Versioning supports them both. 90%+ of the time people mean ASP.NET Core, but every once in a while, a question or issue comes up about the old stack, so I like to clarify. Thanks MS Marketing for making things unambiguously easy to understand! 😵‍💫

Hopefully, that solution works for you.

**Comment by julianalsemmani** [comment]
I got one more question. In the Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer I was using "IApiVersionDescriptionProvider". Is there any alternatives for this in Asp.Versioning?

I tried installing Asp.Versioning.WebApi, but do I need Asp.Versioning.Mvc as well?

**Comment by julianalsemmani** [comment]
Solved this! Figured out that I needed to use Asp.Versioning.Mvc and not the Asp.Versioning.WebApi!

@commonsensesoftware Thanks for helping out with the other stuff! I'll close this issue! 😄
