### ISSUE TITLE
Swashbuckle documentation inconsistent with examples

### ISSUE THREAD

**Issue by thatstatsguy** [dotnet/aspnet-api-versioning#1071]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Context: I'm currently exploring using the aspnet api versioning in our code base.

Problem: the documentation at the link below
https://github.com/dotnet/aspnet-api-versioning/wiki/Swashbuckle-Integration

is inconsistent with the examples provided here

https://github.com/dotnet/aspnet-api-versioning/blob/main/examples/AspNet/WebApi/OpenApiWebApiExample/SwaggerDefaultValues.cs

The second one is correct based on how the interface has been implemented. I can't see any documentation on how to contribute to the Wiki so logging here in the interim

### Expected Behavior

N/A

### Steps To Reproduce

N/A

### Exceptions (if any)

N/A

### .NET Version

N/A

### Anything else?

N/A

**Comment by commonsensesoftware** [comment]
Which platform are you targeting? The wiki shows both ASP.NET platforms. You said:

>The second one is correct based on...

This leads me to believe that you are targeting ASP.NET Core; however, the link you included in the issue is for ASP.NET Web API. Despite the term _Web API_ being used pretty loosely, that was actually the name of the platform on classic ASP.NET. Thanks Microsoft Marketing. 😖 I make it a point to call out the differences in platform wherever I can, but the names are similar (and out of my control). I suspect what you want is:

https://github.com/dotnet/aspnet-api-versioning/tree/main/examples/AspNetCore/WebApi/OpenApiExample

assuming that you are using controllers.

**Comment by thatstatsguy** [comment]
Thanks so much for the reply @commonsensesoftware. I see what you mean (and now I look a bit silly). 

That is indeed what I'm looking for! Closing this for now
