### ISSUE TITLE
swagger.json file not found after update 

### ISSUE THREAD

**Issue by PouryaNoufallah96** [dotnet/aspnet-api-versioning#1084]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Describe the bug

My application works fine completely with version 8.0.0 but when I upgrade to version 8.1.0 the swagger/index.html will load but it says : 
Fetch error
Not Found /swagger/v1/swagger.json

### Steps To Reproduce

i dont change anything at the configuration at all except package version.
the result with v 8.0.0:
![image](https://github.com/dotnet/aspnet-api-versioning/assets/49477528/0fd64923-f6a7-4714-aaf8-f96db3b64536)

and with v 8.1.0:
![image](https://github.com/dotnet/aspnet-api-versioning/assets/49477528/d2c083b4-eda1-4e9a-af63-d96d2cb437bb)

### .NET Version

8.0.204

**Comment by commonsensesoftware** [comment]
This isn't very much information to go on. What's the error? It will be reported to the console. My initial guess is that there are  two or more types with the same name, but in different .NET namespaces. A namespace is meaningless to an OpenAPI document and will lead to a naming collision.

Sharing a repro or, at least, your configuration would be helpful.

**Comment by commonsensesoftware** [comment]
The configuration looks ok. I presume you are using _Minimal APIs_; otherwise, you don't need `EnableApiVersionBinding()`. Which IDE are you using? VS? VS Code? If it's not going to the console, there should be something going the debug output. When I've see Swashbuckle errors in the past, that's how I determine the problem.

It might be worth checking the _Break On All Exceptions_ option so that you see any _First Chance Exceptions_. If you can't see or find an error, is there any way to get a bare bones repro? An exception is happening, but I don't know what it is or how to help you find it. Once I know that the error is, I can provide more guidance.

**Comment by commonsensesoftware** [comment]
Gotcha. Yes, the would work when the APIs are called directly. This is specifically limited to generating the OpenAPI document via Swashbuckle. My recommendation would be to comment **all** of the APIs save one. Run it and make sure the OpenAPI document is generated and the Swagger UI comes up. Assuming that works, continue uncommenting one API at a time until you find the offending API that is causing the problem. If you can share the signatures or definitions of the offending APIs, I _might_ be able to provide better direction.

**Comment by commonsensesoftware** [comment]
Glad you found a solution. You _should_ be able to use a group name though. API Versioning will collate and use the API version as the group name by default, but you are _supposed_ to be able override and/or combine the two. I don't messing with a lot of configurations for _Minimal APIs_, but it _should_ work. As I recall `WithGroupName` should register the same metadata as `[ApiExplorerSettings(GroupName="")]`. I may need to take a peek to verify things are working correctly. Thanks for providing all of the details.
