### ISSUE TITLE
CurrentImplementationApiVersionSelector behaves differently based on whether an operation still exists on latest API version

### ISSUE THREAD

**Issue by officeSpacePirate** [dotnet/aspnet-api-versioning#1090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

To preface, one of the projects I work on had not updated since 5.0.0 (apparently we didn't catch the name change), so I realize this might be a dated report. However I couldn't find a workaround in the past issues, so I'm hoping someone can help.

As of 5.1.0 (before the name change), the behavior of the `CurrentImplementationApiVersionSelector` has changed so that only operations or perhaps routes that still exist on the latest version of the API actually work. I believe that `ReportApiVersions` has also changed since this time because a route that does not exist for the latest version of an API now reports that version in its `api-supported-versions` header, which was not previously the case. After reading several issues such as https://github.com/dotnet/aspnet-api-versioning/issues/679, I gather that you guys went with a solution that saved overhead in favor of granularity.

### Expected Behavior

The issue my team is now facing is that upgrading becomes a breaking change for clients of our API. For example, given:

```c#
// Program.cs

builder.Services.AddApiVersioning(options =>
{
  options.ReportApiVersions = true;
  options.AssumeDefaultVersionWhenUnspecified = true;
  options.ApiVersionReader = new QueryStringApiVersionReader("version");
  options.ApiVersionSelector = new CurrentImplementationApiVersionSelector(options);
}).AddApiExplorer(options => options.GroupNameFormat = "'v'VVV").AddMvc();

...

// PetsV1Controller.cs

[ApiVersion(1.0, Deprecated = true)]
[ApiController]
[Route("pets")]
public class PetsV1Controller : ControllerBase
{

  [HttpGet("{petId}")]
  public async Task<PetViewModelV1> GetPetAsync(
    [FromRoute] string petId)
  {
    // get pet
  }

  [HttpGet("{petId}/vaccinations")]
  public async Task<IEnumerable<VaccinationViewModelV1>> GetPetVaccinationsAsync(
    [FromRoute] string petId)
  {
    // get pet vaccinations
  }
}

...

// PetsV2Controller.cs

[ApiVersion(2.0)]
[ApiController]
[Route("pets")]
public class PetsV2Controller : ControllerBase
{

  [HttpGet("{petId}")]
  public async Task<PetViewModelV2> GetPetAsync(
    [FromRoute] string petId)
  {
    // get pet
  }
}
```

In <=v5.0.0, calling `GET /pets/{petId}/vaccinations` without providing `version` behaves exactly the same as `GET /pets/{petId}` does. Today, the latter will work as you would expect and the former returns a 400 Bad Request. Is there a solution or workaround to achieve the previous behavior to prevent having to deal with a breaking change with our clients (it is also our desired behavior in general for this particular API service)? Any guidance would be appreciated.

* Currently on .NET 7.0 attempting to use the latest 7.x versions of your libs; could potentially look at going to 8.x if that would help in any way.

### .NET Version

7.0

**Comment by officeSpacePirate** [comment]
@commonsensesoftware The information above is incorrect. We have a test named for this that started failing after upgrade and I had only manually tested the change. It looks like the issue is actually with our testing rather than behavior of ApiVersioning. I apologize for any wasted time.

I can close this ticket and log another one, but what is the likelihood of implementing a feature/workaround for operation based versioning similar to what I described?

**Comment by commonsensesoftware** [comment]
Honestly, it's been a couple of years now and I don't fully recall if or what the behavior of this situation may have been back in the `5.x` days. You may be right.

One thing that changed in `6.0`+ has to do with the way routing is resolved under the hood. Previously all candidates were considered and the final set was disambiguated by API version. This seems sound and reasonable, but there some edge cases that didn't work correctly; specially, 405, 406/415 when versioning by media type, and arguably even 404. There was also the strange case of a _version-neutral_, which would match absolutely any valid API version, even if it didn't exist anywhere. The primary goal was to fix 405/415, but some other things came with it. These conditions are evaluated higher in the routing system and out of the control of API Versioning. To make things behave correctly, endpoints now anchor on their version when built in the routing tree. A consequence of that behavior is that _some_ scenarios short circuit much earlier in evaluation than before. In this particular case, the candidate is eliminated because there are no matching endpoints. An ancillary benefit is faster evaluation and it's no longer possible to match a nonexistent API version. Those were never goals, but they're nice to have. _Version-neutral_ APIs now have runtime behavior that matches what you see in OpenAPI (e.g. their are in every version, but not versions that don't exist).

Arguably the behavior you are asking for was never intended to work that way. Versions are meant to be collated and matched against an entire logical API, not individual endpoints or actions. The current version should be of the _Pets_ API and not a specific endpoint. Bare in mind that when API Versioning is guiding the routing system, there is very little information available. The best action has to be resolved from nothing more than the incoming request URL and resolved API version. At this point in the pipeline, the possible candidate actions aren't even known yet.

All that being said, there are some options to preserve the old behavior. Since many candidates are eliminated earlier in the pipeline, there are a lot fewer 400 cases where something _could_ match. Remember that API Versioning doesn't know which endpoints can match for the `IApiVersionSelector`. What it does know is that multiple endpoints with the same logical name (not even template) are collated together. `pets/{id}` and `pets/{id:int}` are semantically equivalent, but not the same so grouping on templates is not very feasible. The `IApiVersionSelector` is provided the incoming request and all known, collated versions. If an endpoint has been removed from the API, there is no way for API Versioning to know that at this point in the evaluation.

### Option 1

There are 3 internal variations you could handle:

1. Have the newer versions call into or execute the next version
2. Use URL rewriting and transfer the request
3. Redirect the client with 301 or 308

### Option 2

You know your API better than API Versioning so you know which APIs really exist. There is certainly risk to potentially pull the carpet out from under clients by advancing a version without them knowing about it, but that is up to you. It seems like you have an established behavior.

To match a request to an endpoint that has an API version lower that the collated set of all versions, you would need to have a custom `IApiVersionSelector` that matches the incoming request URL and the current API version. You don't necessarily have to do that for all endpoints, but certainly any that have _current_ versions lower than the highest version of the logical API. This would mean, that if `pets/42/vaccinations` is requested, you would have to map it back to `1.0` since `2.0` is the current version of the _Pets_ API, but that endpoint doesn't exist in it.

### Option 3

If things were working exactly the way you wanted in the old libraries, then you could split your API across implementations with YARP.  Versions 1-(n) would be hosted using the old libraries and host, while new versions are hosted on the new libraries and host. When the older versions are finally sunset, you can shut down the old host and remove YARP if you want to. This is probably the only guaranteed method to ensure there are no runtime behavior changes. You can use `[AdvertiseApiVersions]` to report the existence of API versions that are not in the old API and old versions that don't exist in the new APIs. Clients that request API versions explicitly will get routed to the correct place. To continue routing implicitly, you'd have to specify that in your YARP configuration. I'm not sure how you'd generate that programmatically, but it may be possible.

**Comment by officeSpacePirate** [comment]
Thanks for the thorough response. I'll update here with a decided direction when we're finished in case it's useful to others.
