### ISSUE TITLE
Doesn’t work with new Open API stuff in ASP.NET Core 9

### ISSUE THREAD

**Issue by marinasundstrom** [dotnet/aspnet-api-versioning#1114]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Is there a way to make this work for Minimal API Endpoints in .NET 9?

Routes not showing up in generated spec.

I’m switching from NSwag.

### Expected Behavior

Routes showing up in Open API spec.

### .NET Version

9.0.0-RC

**Comment by commonsensesoftware** [comment]
I'll need some additional information. _"It doesn't work"_ doesn't provide much context. What is your setup? Is there a repro?

The [OpenAPI Minimal API example](../examples/AspNetCore/WebApi/MinimalOpenApiExample) should show everything you need to get things started with _Minimal APIs_ and OpenAPI.

I should also point out that .NET 9 is not yet officially supported because it is not released. A TFM mapping is **only** guaranteed to work with an exact match (e.g. `net8.0` → .NET 8). This is because of a runtime major version bump. Even if things compile, there can be runtime behavioral differences. I've seen it happen. As an army of one, it's difficult to chase pre-releases. It's rare for me to release a version for a pre-release version of .NET. It isn't as trivial as some might think. Nevertheless, the official release is nearing and I intend to get something aligned to that ASAP.

If the provided example is insufficient, I should point out Microsoft's [eShop](https://github.com/dotnet/eShop) application for Aspire uses _Minimal APIs_, OpenAPI, and API Versioning. I collaborated with them on adding it. They appear to have it working without issue. You might want to review that setup (see: [here](https://github.com/dotnet/eShop/blob/main/src/Catalog.API/Apis/CatalogApi.cs#L10))

**Comment by marinasundstrom** [comment]
@commonsensesoftware Excuse me. I was kind of desperate. But it seems that the sample might give me a solution.

Thanks.
