### ISSUE TITLE
[EndpointRouting] - System.NullReferenceException

### ISSUE THREAD

**Issue by AVIILIIX** [dotnet/aspnet-api-versioning#686]
### Preconditions:

- **Microsoft.AspNetCore.Mvc.Versioning**: **4.1.1**
- **Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer**: **4.1.1**
- **Microsoft.AspNetCore.App**: **5.0.0-rc.2.20475.17**
- **Microsoft.NETCore.App**: **5.0.0-rc.2.20475.5** (Also replicable in 3.1)

Extra Packages:
- Microsoft.AspNetCore.Odata: 7.5.0
- Microsoft.AspNetCore.OData.Versioning: 4.1.1
- Microsoft.AspNetCore.OData.Versioning.ApiExplorer: 4.1.1

### Description:

When using EndpointRouting instead of MVC within the next setup in Startup.cs, at every request to an endpoint API-versioning throws an Exception:

`System.NullReferenceException: Object reference not set to an instance of an object.
at Microsoft.AspNetCore.Mvc.Routing.ApiVersionMatcherPolicy.EvaluateApiVersion(CandidateSet candidates, ApiVersion apiVersion)
at Microsoft.AspNetCore.Mvc.Routing.ApiVersionMatcherPolicy.ApplyAsync(HttpContext httpContext, CandidateSet candidates)
at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.SelectEndpointWithPoliciesAsync(HttpContext httpContext, IEndpointSelectorPolicy[] policies, CandidateSet candidateSet)
at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatch|8_1(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task matchTask)
at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`

### Workaround or bad config?

When I configured UseMvc or UseMvcWithDefaultRoute() as shown it next, the message related to "System.NullReferenceException" disappears and everything works perfectly; but the desired scenario is wasn't use MVC due purpose of improve performance (Loading useless dependencies)

`
            ...

            // Enable API Versioning
            app.UseApiVersioning();

            #pragma warning disable
            app.UseMvcWithDefaultRoute();

            // HTTPS only
            app.UseHttpsRedirection();

            ...
`

I tested some scenarios & did some research towards Middleware init. But at this point I don't understand what causes the problem or where it's located or related, maybe some of these I named "useless dependencies" are needed for the right execution of API-Versioning. Unless the unique choice is using MVC, but in the examples provided by the API-Versioning developer team, MVC does not appear anywhere in the code.

### Setup:
Startup.cs

`        public void Configure(IApplicationBuilder app, IWebHostEnvironment env, ILoggerFactory logger, IApiVersionDescriptionProvider provider)
        {
            // Getting Environment
            Environment = env;

            if (env.EnvironmentName.Equals("Development"))
                app.UseDeveloperExceptionPage();
            else
                app.UseHsts();

            // Enable Authentication
            app.UseAuthentication();

            // Enable API Versioning
            app.UseApiVersioning();

            // HTTPS only
            app.UseHttpsRedirection();

            // Enable Routing
            app.UseRouting();

            // Enable Authentication
            app.UseAuthorization();

            // Enable MVC properties
            app.UseEndpoints(options =>
            {
                options.Select().Filter().Expand().OrderBy().MaxTop(100).Count();
                options.MapODataRoute("", "", GetEdmModel());
                options.MapControllers();

                // Workaround: https://github.com/OData/WebApi/issues/1175
                //options.EnableDependencyInjection();
            });

            // Enable Index
            app.UseDefaultFiles(new DefaultFilesOptions
            {
                DefaultFileNames = new List<string> { "index.html" }
            });
            app.UseStaticFiles();
        }
`

`        public void ConfigureServiceMVC(ref IServiceCollection services)
        {
            //Add OData compatibility
            services.AddOData();
            services.AddODataQueryFilter();

            //Add Filters
            services.AddControllers(options =>
            {
                options.EnableEndpointRouting = true;
            });

            services.AddApiVersioning(options =>
            {
                options.DefaultApiVersion = new ApiVersion(1, 0);
                options.ReportApiVersions = true;
                options.AssumeDefaultVersionWhenUnspecified = true;
                options.UseApiBehavior = false;
                options.ApiVersionReader = new HeaderApiVersionReader("x-api-version");
            });

            services.AddVersionedApiExplorer(options =>
            {
                // add the versioned api explorer, which also adds IApiVersionDescriptionProvider service
                // note: the specified format code will format the version as "'v'major[.minor][-status]"
                options.GroupNameFormat = "VVVV";

                // note: this option is only necessary when versioning by url segment. the SubstitutionFormat
                // can also be used to control the format of the API version in route templates
                options.SubstituteApiVersionInUrl = false;
            });
        }`

**Comment by Mhirji** [comment]
@AVIILIIX , I believe that version 4.x of this lib will not run on .net 5.  You will need to use the version 5 package which is currently in RC.

**Comment by commonsensesoftware** [comment]
Thanks @Mhirji.

@AVIILIIX , there's a myriad of issues here, some of which @Mhirji has mentioned.

### Questions and Observed Issues
- It looks like you are targeting .NET 5.0. Are you or are you targeting .NET Core 3.1 with the .NET 5.0 SDK?
- API Versioning support for OData with _Endpoint Routing_ is currently in **rc.2**
- API Versioning for .NET 5.0 is currently in **preview.2**
- The API Versioning .NET 5.0 preview does **not** support OData
   - This requires OData 8.0, which is also in **preview** and is yet another major infrastructure change
   - This will be supported via API Versioning 6.0 for OData and probably won't happen until the 1st of the year
- _Endpoint Routing_ is enabled by default, but since your using OData and not the current RC, it's not supported. This means it should be explicitly disabled as illustrated in the [samples](../blob/release/4.1/samples/aspnetcore/ODataBasicSample/Startup.cs)
  - Your configuration _may_ work, but it should instead be: `services.AddControllers(o => o.EnableEndpointRouting = false)`
- You _almost_ never need to use `app.UseApiVersioning()`
  - It will happen automatically and does every little (it just adds a _feature_ to the request)
  - OData batching is the only known scenario where you need this (because OData doesn't copy the features)
  - In order for `app.UseApiVersioning()` to have any effect, you have to configure `services.AddApiVersioning(o => o.RegisterMiddleware = false)`
- You may have a reason, but changing `UseApiBehvaior = false` will version all controllers, including UI controllers
  - It seems this application is mixed with UI stuff
- There's nothing wrong with it, but FYI, `DefaultApiVersion = new ApiVersion(1,0)` **is** the default
   - So is `ApiVersion.Default`
- `options.SubstituteApiVersionInUrl` is the default so can just remove that
  - This option has no effect unless you are versioning by URL segment, which you're not (yay!)
- If you want to use OData with _Endpoint Routing_ via the latest RC, you should follow this [sample](../blob/master/samples/aspnetcore/ODataBasicSample/Startup.cs)

>API Versioning only depends on MVC Core, not MVC. It's a very minimal set of dependencies. Starting in ASP.NET Core 3.0+, you reference the framework, the whole framework, and the compiler decides what you need.

That's lot, but hopefully that gets you started. Happy to answer any additional questions.

**Comment by commonsensesoftware** [comment]
I'm working on some issue clean up. There _is_ a version of everything working with _Endpoint Routing_ for API Versioning and OData on .NET Core 3.1. .NET 5.0 is still not an option because OData won't support it until 8.0 - though that appears to be close. The current OData examples demonstrate how to make things work.

If this is now solved or you've gone another way, let me know. Thanks.

**Comment by commonsensesoftware** [comment]
This issue seems to have been resolved or abandoned. OData 8.0 with .NET 6.0 and Endpoint Routing is now supported in `6.0`:

- [Asp.Versioning.OData](https://www.nuget.org/packages/Asp.Versioning.OData)
- [Asp.Versioning.OData.ApiExplorer](https://www.nuget.org/packages/Asp.Versioning.OData.ApiExplorer)

If you were still encountering any of these issues, they should be resolved now. Thanks.
