### ISSUE TITLE
can't bind parameter in odata route template

### ISSUE THREAD

**Issue by anranruye** [dotnet/aspnet-api-versioning#692]
base on newest aspnetcore odata swagger sample project, remove v1 and v2 orders controllers, add [ApiVesion("2.0")] and [ApiVersion("3.0")] to make v3 orderscontroller support for all versions. change parameters named 'key' to 'id' in both odata route template of [ODataRoute] attribute and method body, run the project.

the 'id' parameter can be bound with version v1, but can't be bound with v2 and v3. the parameter remain default value 0.

rollback to Microsoft.AspNetCore.OData.Versioning 4.1.1,  all versions work correctly.

**Comment by anranruye** [comment]
It's strange that i do the above steps again today but i have a different result(previous attempt is made in last week). All three versions failed to bind the 'id' parameter.

first time i guess it might be caused by cache of my web explorer, but in my own application(only use version v1), i can bind the 'id' parameter all the time.  i also test other samples, the 'id' parameter can be bound occasionally, but most times it just remain 0.

This situation confused me.

**Comment by commonsensesoftware** [comment]
Welcome to the world of OData. >_< The rules are never clear in their documentation or examples, but I can tell 100% for certain the expected convention is that all entity identifiers use the `{key}` route parameter. Like everyone else `{id}` feels more natural and something I just _expect_ to work. Sometimes it does and sometimes it doesn't; usually due to some mismatch of configuration and/or attributes. I've tried to be consistent about swapping all parameters from `{id}` to `{key}`, but their might be some left. While you might prefer `{id}` over `{key}`, the effort to make it work consistently isn't worth it.

There's a significant difference in routing between 4.1.1 and 5.0.0. 5.0.0 introduces support for _Endpoint Routing_ with OData. If requests are being dispatched to the correct action, but model binding is incorrect, this is almost certainly caused by OData. This _may_ be a caused by its library changes and/or your particular configuration combination. Whether you're using attribute-routing or convention-based routing, you still end up needing to know quite about the OData routing conventions. If you get it wrong, it can be infuriating. I've only figured out what many of them are by looking at the source code in their repo.

I put out the release candidate to try and flush these types of issues out. I can't really say how many people actually gave it a whirl. Again - if the correct action is being dispatched, then things in API Versioning are almost certainly correct. I'll investigate the setup you've outlined and see if I can repro the scenario. If it's just `{key}` versus `{id}`, I would simply swap it to `{key}` as expected and call it a day. If you _really_ want it to be called `id`, you can always use a hook in Swashbuckle (or generator of choice) to update the API description (e.g. you can display it as `id`, even though it really maps as `key`).

**Comment by anranruye** [comment]
@commonsensesoftware 

Thank you. Yes, the purpose I use ODataRoute attribute and the parameter name 'id' is to change the api document. Your advice helps. But I still think there is something wrong with odata api versioning.

I do understand that the rules in OData libraries are not clear and change from vesion to version. But this time I suppose that the usage of names different from 'key' is in design of odata attribute routing. In page https://docs.microsoft.com/en-us/odata/webapi/attribute-routing  , they use 'id' as identifier but not 'key'. 

In my understanding, odata attribute routing is none-convention routing. That means, I can change controller names, action names and parameter names to whatever I want. I use example projects in odata webapi repo(https://github.com/OData/WebApi) to prove my thought. And it shows me, odata attribute routing just works like what I expected in a none-versioning scenario.

Odata attribute routing should be respected as before, my previous issue is also in this subject.  I can understand the effort to fix this problem might be not worthy since aspnetcore odata 8.0.0 is coming soon. It makes no sence for me to use '{id}' or '{key}'. I just want to tell that something is not working correctly.

**Comment by anranruye** [comment]
Finally I find why all three versions failed to bind the 'id' parameter yesterday.
the 'id' parameter can only be bound with the lowest api version in the application. for SwaggerODataSample project, the lowest version is v0.9 but not v1. in the attempt last week, i remove all v1 controllers so that the lowest version is v1.

**Comment by commonsensesoftware** [comment]
I know it's been a long time, but I wanted to clarify whether you got things working the way you wanted and expected. I'm going through the list of old issues, closing out those are done, and working on fixes. Based on your last comment, it would seem that this issue might be resolved. Thanks.

**Comment by commonsensesoftware** [comment]
There's been no further action on this issue and it appears to have been answered. The forthcoming OData 8 support will provide more flexibility in routing and what you may be accustomed to. Check out the roadmap and latest bits when you have a chance. Thanks.
