### ISSUE TITLE
NullReferenceException in .NET 5 if middleware is injected in the wrong order

### ISSUE THREAD

**Issue by justinbhopper** [dotnet/aspnet-api-versioning#704]
I'm not sure if this is a bug exactly, but I ran into a `NullReferenceException` [here in the ApiVersionRouteConstraint](https://github.com/microsoft/aspnet-api-versioning/blob/dev/chrimart/dotnet5/src/Microsoft.AspNetCore.Mvc.Versioning/Routing/ApiVersionRouteConstraint.cs#L55) due to the middleware not yet having been injected.

In my particular case, the issue turned out to be that `UseApiVersioning()` was registered after `UseRouting()`, rather than before it.  This resulted in the `IApiVersioningFeature` to not yet have been registered in the middleware chain.

I think perhaps just adding a null check here (and probably all other calls for `httpContext.Features.Get<IApiVersioningFeature>()`) and throwing a more informative exception would help.

**Comment by commonsensesoftware** [comment]
Yeah ... doing this setup in the middleware seemed appropriate, but it's honestly not necessary. it can be added on demand. It's reasonable thing to leave current middleware as a no-op and use lazy initialization of the feature in a way that prevents this from happening; especially since reordering the middleware doesn't really matter.
