### ISSUE TITLE
Microsoft.AspNetCore.Mvc.Versioning.Abstractions (NetStandard)

### ISSUE THREAD

**Issue by abbotware** [dotnet/aspnet-api-versioning#713]
I read the conversations about not supporting NetStandard... I get that, but would you consider creating a **Microsoft.AspNetCore.Mvc.Versioning.Abstractions** library that is **NetStandard** and move some of the Attributes?

Let me explain my rational - I have found the WebAPI definitions to be a bit cumbersome and have struggled separating 'Metadata' / 'Contract' definitions from the implementation.  I have (overtime) come up with a clean way to do this that is supported 100% by NetCore using a Decorator / Pimpl pattern.

I want to isolate the contract code ( C# Interface + C# Controller code with Attributes) into a separate library (NetStandard2.x) so it is separate from the implementation

### example

I have a C# interface that I want to be the basis of a REST API

**Contract Library (NetStandard)**

```
   // this single interface drives the controller + implementation
    public interface ISomeObjectController
    {
        Task<SomeObject> GetSomeObject(int id, CancellationToken ct);
     }
```

this controller below has all the Web API attributes and is just a simple wrapper around the implementation... this **could** go into a separate NetCoreApp library... but that just seems like a proliferation of libraries when the interface (above)  and controller (due to the attributes) are what define the REST Contract.

```

    [ApiController]
    [ApiVersion("1.0")]    [This Does Not Work unless I use 4.1.0]
    [Route("api/v{v:apiVersion}/[controller]")]
    public class SomeObjectController : ShimController<ISomeObjectController>, ISomeObjectController
    {
        public SomeObjectController (ISomeObjectController impl)
            : base(impl)
        {
        }

        [HttpGet]
         public Task<SomeObject> GetSomeObject(int id, CancellationToken ct)
        {
            return Impl.GetSomeObject(id, ct);
        }
```

At this point all the metadata driving the Web API definition is completely separate from the below implementation    If the C# interface changes, it will automatically require a change in the Controller and Implementation

**Implementation Library (NetStandard or NetCoreApp)**
```
    public class SomeObjectImplementation : BaseController, ISomeObjectController
    {
        public SomeObjectImplementation (ILogger<SomeObjectImplementation > logger)
            : base(logger)
        {
        }
        public async Task<SomeObject> GetSomeObject(int id, CancellationToken ct)
        {
          /// actual implementation
        }
```

Note that one can also easily inject a mock into SomeObjectController.

**Registration (NetCoreApp)**

```

     // register the wrapper controller
    services.AddMvc()
         .AddApplicationPart(typeof(SomeObjectController).Assembly);

    // register the injected implementations
    services.AddTransient<ISomeObjectController, SomeObjectImplementation >();
```

**Comment by commonsensesoftware** [comment]
A few people have asked about this in the past, but it was mostly related the **ApiVersion** type itself. I'll chalk this up as an enhancement for future consideration, but it has a pretty low priority. A lot of things need to happen to split that out. Fear not! There are still lots of great options for you today.

First, API Versioning doesn't care about attributes at all. This is a common misconception. It only cares about **IApiVersionProvider**. Attributes are just one the ways that this can be realized. Things can also be realized using conventions. You can even define your own conventions.

There are 2 basic ways you can make this work they way you want:

1. Use the _Conventions_ API as is. This may be explicit conventions or a custom convention that reads information from an external source such as a file or database. A key reason for this to exist was to configure controllers that come from an external source or that you might not have source code for.
2. Define your own attribute in an _abstractions_ library that targets .NET Standard and you share across your own libraries. Then create a separate library that understands how to read metadata via a convention and adds it to API Versioning. Only the convention has a direct dependency on API Versioning. If you use attributes, getting it is easy because the **ControllerModel** handed to your convention will have a property with all of the discovered attributes automatically. You need only weed it out of the possibilities and then marry it to the `builder` your convention is provided.

The wiki has documentation on the details for [custom conventions](../https://github.com/microsoft/aspnet-api-versioning/wiki/API-Version-Conventions#custom-conventions). You can also see examples by looking at the **VersionByNamespaceConvention**. The integration is as simple as:

```c#
services.AddApiVersioning(options => options.Conventions.Add(new MyVersioningConvention()));
```

**Comment by commonsensesoftware** [comment]
Closing out as part of _house keeping_. Happy to continue to the discussion or reopen if necessary. Ultimately, I believe what you've asked for is now available.

**Comment by abbotware** [comment]
It does sound like this is exactly what I was looking for - thanks again!
