### ISSUE TITLE
Errors while trying to build solution inside a dev container

### ISSUE THREAD

**Issue by aleks-ivanov** [dotnet/aspnet-api-versioning#763]
I am trying to build the solution inside a dev container with the following config:

- Ubuntu 20.04
- .NET 5
- .NET Core 3.1

Here is the [build log](https://github.com/dotnet/aspnet-api-versioning/files/6955445/build.log.txt).

There are quite a few errors, so am I missing some tooling ?

**Comment by commonsensesoftware** [comment]
You likely have all the required tooling. There isn't anything special you should have to install. Coincidentally, I just ran into the same problem on another project that uses a similar solution/build setup.

The problem is likely two-fold:

- Build scripts should not use literal `/` or `\` 
- Paths are case-sensitive on most Linux-based systems

The last item is likely the primary culprit. I didn't know/recall that Linux file systems are case-sensitive. The standard MSBuild extension points use **Build.Directory.props** and **Build.Directory.targets**. These files exist, but are lowercase. Things work just fine on Windows and most macOS systems. You'll almost certainly run into trouble building on Linux.

Supporting multi-platform builds was never a goal, but I definitely wanted to enable it if possible. This should be an easy fix. I just need to audit the build files. Shouldn't take too long since it's fresh in my mind. I'll consider this a _bug_ since it violates [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment). Frankly, I'm surprised this hasn't come up or otherwise been reported before. Maybe it has, but insufficient details were provided. Thanks for reporting it.

**Comment by aleks-ivanov** [comment]
@commonsensesoftware the capitalization of the three Directory.Build files did enable errorless building of all source and test projects.

Here is the [build log](https://github.com/dotnet/aspnet-api-versioning/files/6961782/build_log.txt).

For the running tests however, currently some require mono as a host and this is the [test log](https://github.com/dotnet/aspnet-api-versioning/files/6961787/test_log.txt).

**Comment by commonsensesoftware** [comment]
As noted, this was primarily due to the casing of MSBuild extension files. GitHub Actions are successfully running on Linux for `ms` (formerly `master`) and `main` which are the branches that matter. `main` also builds successfully on Windows through WSL with Ubuntu. End-to-end tests need to happen on Windows due to the requirement of the full .NET Framework. Thanks for helping drive these fixes.
