### ISSUE TITLE
Multiple versions in Attribute

### ISSUE THREAD

**Issue by JulienM28** [dotnet/aspnet-api-versioning#776]
I wondered if it was possible to add multipla api versions in one attribute to avoid that:

````csharp

    [ApiVersions("1")]
    [ApiVersions("2")]
    [ApiVersions("3")]
    [ApiController]
    [Produces("application/json")]
    public class AlerteController : ControllerBase

````
    
    I wanted to do something like this:
```csharp
    [ApiVersions("1", "2", "3")]
    [ApiController]
    [Produces("application/json")]
    [Route("alertes")]
    public class AlerteController : ControllerBaseCustom
```
    
    Unfortunately with ApiVersionAttribute it's not possible.
But I noticed ApiVersionsBaseAttribute offers the right signature:
  protected ApiVersionsBaseAttribute( params string[] versions )
  
  So I Created an ApiVersionsAttribute inherited from ApiVersionsBaseAttribute and calling the four base signatures.
  It doesn't work.
  
  I tried to reimplement all base class using only IApiVersionProvider
  
```csharp
[AttributeUsage(Class | Method, AllowMultiple = true, Inherited = false)]
    public class ApiVersionsAttribute :/* ApiVersionsBase*/Attribute, IApiVersionProvider
    {
        ApiVersionProviderOptions options = ApiVersionProviderOptions.None;

        readonly Lazy<int> computedHashCode;
        readonly Lazy<IReadOnlyList<ApiVersion>> versions;
        protected ApiVersionsAttribute(ApiVersion version) : this(new[] { version }) { }

        protected ApiVersionsAttribute(params ApiVersion[] version)
        {
            computedHashCode = new Lazy<int>(() => ComputeHashCode(version));
            versions = new Lazy<IReadOnlyList<ApiVersion>>(() => version);
        }

        public ApiVersionsAttribute(string version) : this(new[] { version }) { }

        [CLSCompliant(false)]
        public ApiVersionsAttribute(params string[] version)
        {
            computedHashCode = new Lazy<int>(() => ComputeHashCode(Versions));
            versions = new Lazy<IReadOnlyList<ApiVersion>>(() => version.Select(ApiVersion.Parse).Distinct().ToSortedReadOnlyList());
        }

        ApiVersionProviderOptions IApiVersionProvider.Options => options;

        /// <summary>
        /// Gets or sets a value indicating whether the specified set of API versions are deprecated.
        /// </summary>
        /// <value>True if the specified set of API versions are deprecated; otherwise, false.
        /// The default value is <c>false</c>.</value>
        public bool Deprecated
        {
            get => (options & ApiVersionProviderOptions.Deprecated) == ApiVersionProviderOptions.Deprecated;
            set
            {
                if (value)
                {
                    options |= ApiVersionProviderOptions.Deprecated;
                }
                else
                {
                    options &= ~ApiVersionProviderOptions.Deprecated;
                }
            }
        }

        public IReadOnlyList<ApiVersion> Versions => versions.Value;

        /// <summary>
        /// Returns a hash code for the current instance.
        /// </summary>
        /// <returns>A hash code.</returns>
        public override int GetHashCode() => (computedHashCode.Value * 397) ^ Deprecated.GetHashCode();

        static int ComputeHashCode(IEnumerable<ApiVersion> versions)
        {
            var hashCode = 0;

            using (var iterator = versions.GetEnumerator())
            {
                if (!iterator.MoveNext())
                {
                    return hashCode;
                }

                hashCode = iterator.Current.GetHashCode();

                unchecked
                {
                    while (iterator.MoveNext())
                    {
                        hashCode = (hashCode * 397) ^ iterator.Current.GetHashCode();
                    }
                }
            }

            return hashCode;
        }
    }
```
  
It doesn't work too.

if I use my attribute like this:
```csharp
    [ApiVersions("1")]
    [ApiVersions("2")]
    [ApiVersions("3")]
```
It doesn't work too.

So what I missed to make it working ?

An why ApiVersionAttribute isn't supporting these signatures ?

Thanks.

**Comment by commonsensesoftware** [comment]
What you have _looks_ correct. I suspect that there may be some subtle difference that has been missed in the changes during your various iterations. **ApiVersionsBaseAttribute** is meant to be a base implementation that can be used as an extension point so you don't have to reimplement everything.

There are a few key points about **ApiVersionsBaseAttribute**, however (by design):

- No attribute usage has been specified so you can define whatever you want
- **IApiVersionProvider** is **not** implemented so you have control over _how_ it's done
- **ApiVersionAttribute** and **AdvertiseApiVersionsAttribute** are example implementations

At the end of the day, API Versioning doesn't care about any specific attributes; it only cares whether **IApiVersionProvider** is implemented. **AdvertiseApiVersionsAttribute** is probably the best example of the implementation you are looking for.

The constructors in **ApiVersionsBaseAttribute** that accept **ApiVersion** is the _preferred_ method, but they typically cannot be used due to limitations in the way attributes work (e.g. they only allow constant primitives, arrays, and types). There are many ways the version can be expressed, so the default framework method uses a string that is parsed; that covers everyone. If you intend to version by `<major>` or `<major>[.<minor>]`, then you can do _better_ by using the integer components. This would allow:

```c#
[ApiVersion(1)]    // 1.0
[ApiVersion(1,1)] // 1.1
[ApiVersion(2)]    // 2.0
```

With a little math _magic_ you can even make it work with `double` or `decimal` so that you have:

```c#
[ApiVersion(1.0)]
[ApiVersion(1.1)]
[ApiVersion(2.0)]
```

or, more in line with your goals:

```c#
[ApiVersions(1.0, 1.1, 2.0)]
```

For example:

```c#
using static Microsoft.AspNetCore.Mvc.Versioning.ApiVersionProviderOptions;
using static System.AttributeTargets;

[AttributeUsage(Class | Method, AllowMultiple = true)]
public sealed class ApiVersionsAttribute : ApiVersionsBaseAttribute, IApiVersionProvider
{
    private ApiVersionProviderOptions options = None;

    public ApiVersionsAttribute(params double[] versions)
        : base( ToApiVersions( versions) ) { }

    public bool Deprecated
    {
        get => options.HasFlag( Deprecated );
        set
        {
            if ( value )
            {
                options |= Deprecated;
            }
            else
            {
                options &= ~Deprecated;
            }
        }
    }

    private static ApiVersion[] ToApiVersions( double[] versions )
    {
        var apiVersions = new ApiVersion[versions.Length];

        for ( var i = 0; i < versions.Length; i++ )
        {
            var version = versions[i];
            var bits = decimal.GetBits( version );
            var scale = (bits[3] >> 16) & 31;
            var major = decimal.Truncate( version );
            var minor = (int) ((version - major) * Math.Pow(10, scale));

            apiVersions[i] = new ApiVersion((int) major, minor);
        }

        return apiVersions;
    }
}
```

As for the background and history as to why **ApiVersionAttribute** only accepts a single version by default - this was by design. There was consideration for multiple, but there were some key factors:

- The expected, primary use case as a single API version, which makes `[ApiVersions(1.0)]` _less_ explicit as there's only one
- Version interleaving is 100% supported, but discouraged (for clarity)
- Any _sound_ versioning policy, say `N-2`, means that there will likely never be more than 1-3 **ApiVersionAttribute** instances applied

In the very early days of the project, even before GitHub, this option was available. After observing confusion and misuse among teams, I ultimately went with the single version option. However, rather than just completely remove the possibility and make developers do a bunch of work on your own, the necessary base implementations have been retained to make extension very easy. This has also paid dividends for scenarios I never thought of or anticipated for extensibility.

**Comment by JulienM28** [comment]
Thank you for your explanations.

I tried    [AdvertiseApiVersions("1", "2", "3")] 
Cause it's exactly what I wanted to do, but It doesn't wook too.

I retried my own Attribute with inheritance, and it doesn't work too.

````csharp
using static System.AttributeTargets;

    [AttributeUsage(Class | Method, AllowMultiple = true)]
    public sealed class ApiVersionsAttribute : ApiVersionsBaseAttribute, IApiVersionProvider
    {
        private ApiVersionProviderOptions options = ApiVersionProviderOptions.None;
        public ApiVersionsAttribute(params ApiVersion[] versions) : base(versions)
        {
        }


        public ApiVersionsAttribute(params string[] versions) : base(versions)
        {
        }

        public ApiVersionProviderOptions Options => options;

        public bool Deprecated
        {
            get => (options & ApiVersionProviderOptions.Deprecated) == ApiVersionProviderOptions.Deprecated;
            set
            {
                if (value)
                {
                    options |= ApiVersionProviderOptions.Deprecated;
                }
                else
                {
                    options &= ~ApiVersionProviderOptions.Deprecated;
                }
            }
        }

        /// <summary>
        /// Returns a hash code for the current instance.
        /// </summary>
        /// <returns>A hash code.</returns>
        public override int GetHashCode()
        {
            var hashCode = (base.GetHashCode() * 397) ^ Deprecated.GetHashCode();
            hashCode = (hashCode * 397) ^ 1;
            return hashCode;
        }
    }
````

**Comment by commonsensesoftware** [comment]
I'm not sure what you've missed, but for your convenience, I've attached [a complete, working repro](https://github.com/dotnet/aspnet-api-versioning/files/7181242/Issue776.zip). Tweak it as necessary to suite your needs.

The following vanilla controller puts everything together:

```c#
[ApiVersions(1.0, 1.1, 2.0)]
[ApiController]
[Route("[controller]")]
public class ValuesController : ControllerBase
{
    [HttpGet]
    public IActionResult Get(ApiVersion version) =>
        Ok(new { ver = version.ToString(), method = nameof(Get) });

    [HttpGet("{id}")]
    [MapToApiVersions(1.0, 1.1)]
    public IActionResult Get(string id, ApiVersion version) =>
        Ok(new { id, ver = version.ToString(), method = nameof(Get) });

    [HttpGet("{id}")]
    [MapToApiVersions(2.0)]
    public IActionResult GetV2(string id, ApiVersion version) =>
        Ok(new { id, ver = version.ToString(), method = nameof(GetV2) });
}
```

### Summary of Results
| Request | Response | Body |
| ---- | ----------- | ----- |
| `GET values?api-version=1` |  200 | `{"ver": "1", "method": "Get"}` |
| `GET values?api-version=1.1` |  200 | `{"ver": "1.1", "method": "Get"}` |
| `GET values?api-version=2.0` |  200 | `{"ver": "2.0", "method": "Get"}` |
| `GET values?api-version=3.0` |  400 |  |
| `GET values/42?api-version=1.0` |  200 | `{"id": "42", "ver": "1.0", "method": "Get"}` |
| `GET values/42?api-version=1.1` |  200 | `{"id": "42", "ver": "1.1", "method": "Get"}` |
| `GET values/42?api-version=2.0` |  200 | `{"id": "42", "ver": "2.0", "method": "GetV2"}` |
| `GET values/42?api-version=3.0` |  400 |  |

**Comment by JulienM28** [comment]
It seems the issue is coming from elsewhere.
We use api/{version}/controller/action route template.

I Assume there's something wrong in the matter we use it.

Thank you very much for your help, i'll wcontinue to investigate the issue and teel you when I'll found the solution.

Thanks

**Comment by JulienM28** [comment]
I finally found out the issue.
It was an issue with our Api versioning / swagger method.

Finaly I made it working with some tweaks.

Thank you for your help.
