### ISSUE TITLE
Versioned API explorer hides query parameters

### ISSUE THREAD

**Issue by acohenOT** [dotnet/aspnet-api-versioning#783]
Checkout, build, and run project with Visual Studio 2019 or Visual Studio Code.
https://github.com/acohenOT/SwaggerTest

Expand /api/v1/Weather/test
Notice that "version" query parameter is missing

Controller decorators
```c#
[ApiController]
[Route("api/v{version:apiVersion}/[controller]")]
[ApiVersion("1.0")]
```

GET method with parameters
```c#
[HttpGet]
public void Get(int param1, int version)
{
}
```

Swagger configuration options:
```c#
services.AddVersionedApiExplorer(options =>
{
    // add the versioned api explorer, which also adds IApiVersionDescriptionProvider service
    // note: the specified format code will format the version as "'v'major[.minor][-status]"
    options.GroupNameFormat = "'v'VVV";

    // note: this option is only necessary when versioning by url segment. the SubstitutionFormat
    // can also be used to control the format of the API version in route templates
    options.SubstituteApiVersionInUrl = true;
});
```
![image](https://user-images.githubusercontent.com/34688558/135552971-073dc210-df06-44b1-a048-0bb013225135.png)

Expected only the route parameter "version" to be replaced with "v1" but not the query parameter.

Specifying the parameter name allows it work as expected.

GET method with parameters
```c#
[HttpGet]
public void Get(int param1, [FromQuery(Name = "version")] int version)
{
}
```

**Comment by commonsensesoftware** [comment]
In short, this _is_ the expected behavior.

The default configuration is not intended to be 100% perfect for OpenAPI because that's an ancillary goal. However, depending on your setup, it will likely _just work_. The default configuration enables versioning by query string and URL segment (🤮) because they tend to be the most common. That doesn't always play well with API documentation.

It is _better_ to explicitly indicate which methods you want you. While you _can_ combine these two methods (it is the default after all), it's more likely that you only want to version by query string or URL segment - not both. You can limit it to just one with:

```c#
services.AddApiVersioning(options => options.ApiVersionReader = new UrlSegmentApiVersionReader();
```

or

```c#
services.AddApiVersioning(options => options.ApiVersionReader = new QueryStringApiVersionReader();
```

For OpenAPI documentation, you **cannot** have the same parameter more than once. Similarly, if you are versioning by URL segment (or support it by config), then that takes precedence because path segments are required by spec. Once found, other API version parameters and their location (e.g. header or query) are removed. I _think_ it can continue working by media type, but that would still be strange IMO. Once this is done, you'll have a single API version route parameter located in the path with a default value of the corresponding API version.

Most people that version by URL segment do not want to the API version to be a parameter in documentation. The `ApiExplorerOptions.SubstituteApiVersionInUrl  = true` will, thus, format (also controlled by options), replace the value in the route template, and completely remove the parameter (as though it doesn't exist). Setting this option to `false` or leaving it as the default will retain the parameter as expected.

I'm honestly not sure how you got this to work at all. It shouldn't be possible. I'm guessing this _may_ be due to the difference in type or order in which the parameters are discovered. You have a route parameter `version` (as you named it) for the API version in the route template **and** you have query parameter named `version`. Having two different action parameter with the same name is a mistake.

The API version is **never** just a integer. You cannot receive the value that way. If you want the API version passed to you action, then you just need:

```c#
[HttpGet]
public IActionResult Get(int param1, ApiVersion version) => Ok();
```

The **ApiVersion** type has a special model binder that knows how to provide the current API version to your action. `int version` will **never** match that. If you really want both parameters, then you should rename one of them. Since the API version parameter is removed, I would recommend changing that one since it will have zero effect on documentation as it is ultimately removed; something like `{ver:apiVersion}` where `ver` is the new name.

**Comment by acohenOT** [comment]
Thank you for the information. In my case, the `version` query parameter is not intended to be the API version. it's a parameter for the API itself.

**Comment by commonsensesoftware** [comment]
Fair enough. I would recommend using a different name for the API version route parameter then. It _should_ work the way you expect after that, which includes not having to use `[FromQuery]` (although that's not _wrong_).

Remember that route parameters take the form of `{ <name> [: <constraint> ] } `. `apiVersion` maps to the **ApiVersionRouteContraint**. If you _really_ want to, this name can be changed in `ApiVersioningOptions.RouteConstraintName`. The name you use for the route parameter is up to you. You can use whatever you want, but `version` is common. Since this conflicts with another parameter you need, I recommend another name such as `ver` or `apiVersion`.

**Comment by acohenOT** [comment]
Yes, good point. To avoid a breaking change, I need the query parameter to be `version` but I think I will change the api version to be `apiVersion`. Thanks for suggestions.
