### ISSUE TITLE
Declared vs. Implemented versions

### ISSUE THREAD

**Issue by anat-gilenson** [dotnet/aspnet-api-versioning#784]
I see `ApiVersionModel` includes Declared, Implemented, Supported and Deprecated. I understand Implemented is the combination of Supported and Deprecated. But what is the difference between Implemented and Declared and when is it being used?

I see for example Declared isn't considered when aggregating ApiVersionModels:
[https://github.com/dotnet/aspnet-api-versioning/blob/2c22daaf0bd7dba90d2d7a10737aa630b9c3e62b/src/Common/Versioning/ApiVersionModelExtensions.cs#L97](https://github.com/dotnet/aspnet-api-versioning/blob/2c22daaf0bd7dba90d2d7a10737aa630b9c3e62b/src/Common/Versioning/ApiVersionModelExtensions.cs#L97)

Thank you!

**Comment by commonsensesoftware** [comment]
This is a really good question. I don't know that there is a single place (not even in the wiki) that outlines all the set terminology. For clarity, it as follows:

- **Supported** - All supported versions for a resource (e.g. API)
- **Deprecated** - All deprecated versions for a resource; expected to be sunset by policy in the future
- **Implemented** - `Supported + Deprecated`
- **Mapped** - The versions mapped to a particular action, but does not _declare_ them; this is how _version interleaving_ is achieved
- **Declared** - The versions declared by an action or all actions on a controller
- **Advertised** - The versions known to be `Supported` and/or `Deprecated` across different implementations; for example, using isolated deployments with a gateway (also see [Version Advertisement](../wiki/Version-Advertisement))

**Declared** versions are ultimately used to determine how to whittle down the candidates. **Mapped** versions are very similar, but never _declare_ anything. A **Mapped** version is used to disambiguate `Get` vs `GetV2` if you _interleave_ versions on the same controller.  **Advertised** is pure metadata; these versions will never map to an implementation. The **Supported** and **Deprecated** versions are aggregated across all APIs for the same resource. There are many possible uses for that information, such as by the **IReportApiVersions** service that outputs the `api-supported-versions` and `api-deprecated-versions` headers when `ApiVersioningOptions.ReportApiVersions = true` or `[ReportApiVersions]` is applied.

**Declared** versions cannot be aggregated because they are specific to the action or controller they are defined on. The **IApiVersionProvider** and **ApiVersionProviderOptions** determine how the metadata is interpreted. By the time it's down to an **ApiVersionModel**, it no longer matters if a **Supported** or **Deprecated** API version was declared or merely advertised. **Declared** and **Mapped** API versions also become indistinguishable in the model because there is no difference in terms of using the API version as a discriminator between actions at that point. That _might_ sound confusing, but **Mapped** API versions never contribute to the known sets **Supported** or **Deprecated** API versions.

I hope that helps clarify things. I'm happy to elaborate further, if need be.

**Comment by anat-gilenson** [comment]
Thank you so much for the quick and elaborate response @commonsensesoftware !

Can you please clarify what do you mean by "resource"?
Is it identified by a controller's route attribute? For example - are the routes "resource" and "resource/source" are considered routes for two different resources? 

To put my question in the context of my problem - I'm trying to understand what versions does my `ApiVersionSelector` get when it gets called with `SelectVersion` (I'm using Asp.Net core 3.1). Debugging my code, I see it gets a model which has 'Supported' and 'Implemented' which contains versions of candidates that match my request only. I want to make sure I won't get versions of other routes.

And digging a little dipper just out of curiosity :) How do you actually fetch these versions for `SelectVersion`? 
Examining the code it seems `GetApiVersionModel` is called on every valid candidate's `ActionDescriptor` with the `Explicit` ApiVersionMapping:
[https://github.com/dotnet/aspnet-api-versioning/blob/2c22daaf0bd7dba90d2d7a10737aa630b9c3e62b/src/Microsoft.AspNetCore.Mvc.Versioning/Routing/ApiVersionMatcherPolicy.cs#L166](https://github.com/dotnet/aspnet-api-versioning/blob/2c22daaf0bd7dba90d2d7a10737aa630b9c3e62b/src/Microsoft.AspNetCore.Mvc.Versioning/Routing/ApiVersionMatcherPolicy.cs#L166)
What does Explicit and Implicit mean in this context? Why would you fetch the Action's ApiVersionModel property on `Explicit` and the controller's one on `Implicit`?

**Comment by commonsensesoftware** [comment]
`resource`, by definition would be - yes. The segments in a URL path do **not** convey any hierarchy whatsoever, but human beings tend to make this assumption. The path might _look_ like a folder, but it's not. HTTP is a message-based protocol. Those messages _tend_ to be resource-oriented; meaning, they revolve a particular entity. For example, `order/123` might identify a specific _Order_ resource. Note that the identifier of the order in HTTP and REST parlance is **not** `123`, it's `order/123`. That is also why, despite its popularity, versioning by URL segment is not RESTful - it violates the _Uniform Interface_ constraint. `v1/order/123` and `v2/order/123` are not two different resources (e.g. orders), or they shouldn't be anyway, they are different _representations_.

The way aggregation of resources and API versions work in API Versioning is keyed off of your controller's name - not the route template. While it might seem sensical to use the route template, there are many variances that are not easily solved. For example, `order/{id}` and `order/{id:int}` are semantically equivalent, but different templates. The is a very simple scenario, but it can be much more complex. Instead, APIs are grouped by the controller's name. In general, the controller's name tends to refer to the corresponding resource. For example, you'd expect `order` to correspond to the **OrderController**. The `Controller` suffix is dropped off by convention automatically. It is, however, possible to specify the name other ways; for example, via `[ControllerName("...")]`. The name is the only consistent piece of information to logically group on.  Knowing that information is how you can be sure the aggregated versions contain the correct version set.

It doesn't come up often, but I've seen people try to differentiate similarly named resources with different paths. For example, `order` and `admin/order` or something along those lines. People that do this invariably do so for authorization purposes or ever-so-slightly different representations. These are cross-cutting concerns. There should be one, and only one, way to refer to a the same resource. Security extensions, formatters, and so on can be used to solve those other differences.

All versions are collated at application startup and are invariant after that. If you really want to dig into the proverbial weeds, you want to look at the [ApiVersioningApplicationModelProvider](../blob/master/src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/ApiVersioningApplicationModelProvider.cs). Keep in mind that API versioning does not care about specific attributes, it only cares about **IApiVersionProvider**. API versions can, therefore, be provided by attributes, conventions, or any other discoverable source. You can chose to extend the built-in attributes or roll your own from scratch. The provider collates all that information and then associates the constructed **ApiVersionModel** with the action.

Explicit vs implicit has to do with what happens in the absence of information. Consider:

```c#
[ApiController]
[Route("[controller]")]
public class OrderController : ControllerBase
{
   [HttpGet("{id}")]
   public IActionResult Get(string id) => Ok(new Order(){ Id = id });
}
```

This might have the appearance of being _unversioned_, but that is a false assumption. This controller will have the implicit version of `ApiVersioningOptions.DefaultApiVersion` which defaults to `1.0`. This addresses the problem of both ensuring every controller has some version, even if you don't touch it and prevents you from having to retrofit tens or even hundreds of controllers when you choose to opt into versioning. As soon as **any** versions are explicitly applied, be it attributes or conventions, then this rule is out the window. This ensures you have a way to supplant implicitly applied versions.

Now consider:

```c#
[ApiVersion("2.0")]
[ApiController]
[Route("[controller]")]
public class OrderController : ControllerBase
{
   [HttpGet("{id}")]
   public IActionResult Get(string id) => Ok(new Order(){ Id = id });
}
```

This controller is explicitly versioned so `ApiVersioningOptions.DefaultApiVersion` is ignored and only `2.0` exists. You could, of course, explicitly add `1.0` as well if you wanted to preserve both. At the end of the day, the routing system only cares about actions (aka _endpoints_). If the controller is `2.0`, then what version is `Get`? The answer is surprising - none. The API version information is purely metadata, which `Get` doesn't have. We still need this information, so how do we get it; we look at the controller. This means that `Get` is _implicitly_ `2.0`.

Now let's consider a final absurd and contrived example:

```c#
[ApiVersion("1.0")]
[ApiVersion("2.0")]
[ApiController]
[Route("[controller]")]
public class OrderController : ControllerBase
{
   [HttpGet("{id}")]
   public IActionResult Get(string id) => Ok(new Order(){ Id = id.ToString() });

   [MapToApiVersion("2.0")]
   [HttpGet("{id:int}")]
   public IActionResult GetV2(int id) => Ok(new Order(){ Id = id });

   [ApiVersion("3.0")]
   [HttpGet("{id:int}")]
   public IActionResult GetV3(int id) => Ok(new Order(){ Id = id });
}
```

In this scenario, `Get` implicitly maps to `1.0`. It **only** maps to `1.0` because there is an explicit mapping to `2.0`. If that did not exist, then `Get` would implicitly map to `1.0` and `2.0`. Naturally, this means that `GetV2` maps to `2.0` and **only** `2.0`. Just like the implicit rule at the controller-level, once there are any attributes or conventions applied at the action-level, implicit matching is ignored. Finally, `GetV3` explicitly _declares_ `3.0` which completely ignores the controller-level version information. While that is supported, it's rather inconvenient to do so.

In terms of matching, explicit matches always take precedence. If there are no explicit matches, then and only then, implicit matches will be considered. What is finally passed to the selector can be seen inside [TrySelectApiVersion](../blob/master/src/Microsoft.AspNetCore.Mvc.Versioning/Routing/ApiVersionMatcherPolicy.cs#L211). The **ApiVersionModel** of each remaining, valid candidate is aggregated and then passed to `IApiVersionSelector.SelectApiVersion`. At this point, you should expect candidates that all match the incoming request. The mental model for routing with API Versioning should be the same as it always was, but with the addition of _"How to I disambiguate duplicate routes?"_ - by API version of course. While it's technically possible to have API versions aggregated incorrectly if the route templates overlap with different controller names, I call caveat emptor because you've done something strange IMO. That is addressable by change routes, controller names, or extending/customizing things to distinguish the differences.

I hope that helps clear things up.

**Comment by commonsensesoftware** [comment]
Given the age and idleness of this issue, I believe it has been sufficiently answered and reached its conclusion. If you have more questions or would like to continue the conversation, feel free to reply or reopen the issue. Thanks.
