### ISSUE TITLE
Executing custom ApiVersionSelector by always nullifying the API version

### ISSUE THREAD

**Issue by anat-gilenson** [dotnet/aspnet-api-versioning#785]
I understand that currently, `ApiVersionSelector` is being called only when the API version is null and `AssumeDefaultVersionWhenUnspecified` is true. 
We'd like to execute our custom `ApiVersionSelector` even if the version isn't null. In fact, our requests are forwarded from a proxy that forces every request to contain a version from a closed set of versions it declares so we never expect null in our service. To execute our `ApiVersionSelector` when the version isn't null, we created and configured a custom ApiVersionReader which always returns null. 

What are the risks for such an approach? 

Thank you!

**Comment by commonsensesoftware** [comment]
I believe there actually may be some other cases for OData now that use **IApiVersionSelector**, but - in general - you are right. The **IApiVersionSelector** is _meant_ to serve the purpose: _"Given a request and API version model, select the most appropriate API version"_.

The `AssumeDefaultVersionWhenUnspecified` option is, unfortunately, a highly abused feature. The sole purpose of that feature is meant for backward compatibility. Your API always had _some_ version, even if it's not explicitly modeled in your code; for example, you might call it _Version 1_ or the _Initial Version_. By design, API versioning requires a version for everything; versioning is explicit. This forced behavior would be problematic for existing clients because they were not previously required to provide an API version and they don't know how to. Breaking the client or forcing them to upgrade is assumed to not be an option. To solve that problem, `AssumeDefaultVersionWhenUnspecified` enables _assuming_ some default version if the client doesn't specify one. That finally gets us to the point of _"If a client doesn't specify a version, how should the default version be determined?"_. There are several methods, but this is delegated to the **IApiVersionSelector** which has a number of out-of-the-box implementations. Ultimately, `IApiVersionSelector.SelectApiVersion` is **only** called if no API version was specified **and** `ApiVersioningOptions.AssumeDefaultVersionWhenUnspecified = true`.

The reason for this behavior is simple - the client **always** has to specify the API version they want. As previously mentioned, the one and only exception to this rule is for backward compatibility and only if you enable it. At the end of the day, every API still has a corresponding API version. Unfortunately, many people think of the API version and pairing to the implementation code, but that's the wrong way to think about it. HTTP _is_ the API. HTTP doesn't have _verbs_, it has methods. A `GET` request should be thought of more like `http.get(request)`. An API version is, therefore, much more like a media type, which is why that's the only approach Fielding accepts (BTW: the GitHub API versions that way). If you accept that, then not specifying the API version would be like not specifying the a media type in request. You can't guarantee the client or server will understand each other. Most APIs today will use JSON, but not just any JSON; there's an agreed upon format (e.g. media type). If there is more than one variant, that is disambiguated by API version over the wire. The corresponding code might be completely different, but that is purely an implementation detail.

All of that said, if you get down to a part where you allow a client to not specify an API version and route them _somewhere_, how will you know it's the right place (e.g. what the client wanted)? The client **has** to say `values/123?api-version=1.0` so the server can decide if it's something it can provide. If it can't provide it, then it has to respond appropriately. If the client doesn't do that then the server is guessing what the client wants, which is bad. A server cannot guarantee that the client uses a [Tolerant Reader](http://servicedesignpatterns.com/WebServiceEvolution/TolerantReader), even if most do. That means if the client expects a `1.0` response, but doesn't communicate that to the server and the server responds or redirects to a `3.0` response, the client may break. If you go down this path, you - in effect - negate the purpose and value of API versioning.

If a client can support more than one version, this can be achieved with _API version negotiation_. There are a few ways this can be done.

### Option 1
Allow multiple API versions to be specified during the request and select the best one. The `Accept` header allows specifying media types with a _quality_. Only the **MediaTypeApiVersionReader** allows multiple, different API versions to be provided out-of-the-box. The default implementation **always** selects the API version with the highest quality or value. It would be pretty easy to create an **IApiVersionReader** that could handle that. The real challenge is you may not know which API version is most appropriate until later in the pipeline because there won't be any candidates - yet.

### Option 2
It's not really an _exception_ per se, but an API _can_ be _version-neutral_. That means the API accepts any and all versions, including none at all. A neutral endpoint can be combined with reporting API versions for the client to select from. This concept was intentionally baked in since the beginning for tools and/or client version negotiation. The most sensible approach is to use `OPTIONS`, but if that is a challenge due to CORS, it could just as easily be achieved with `HEAD`.  For example,

```http
OPTIONS values HTTP/2
Host: localhost
```

```http
HTTP/2 200 OK
Allow: GET, OPTIONS
Cache-Control: max-age=86400
Api-Supported-Versions: 1.0, 2.0, 3.0
```

The client can then select from the reported API versions. If a version is reported deprecated (in `api-deprecated-versions`), it might be ignored and log telemetry for someone to follow-up on. Some level of caching would potentially be useful as well. Again, the server should _tell_ the client how long they can cache a response. The client shouldn't assume anything. A client should only _consider_ falling back to their own behavior if the server doesn't provide it.

Implementing such an action would look something like:

```c#
[ApiController]
[Route("[controller]")]
public class ValuesController : ControllerBase
{
   [HttpOptions]
   [ApiVersionNeutral]
   [ReportApiVersions] // reports 'api-supported-versions' and 'api-deprecated-versions' for '~/values'
   public IActionResult Options()
   {
      Response.Headers.Add("Allow", new StringValues(new[]{"GET", "OPTIONS"}));
      Response.GetTypedHeaders().CacheControl = new()
      {
         MaxAge = TimeSpan.FromDays(1d),
      };
      return Ok();
   }
}
```

I hope that helps.

**Comment by commonsensesoftware** [comment]
Some final thoughts on this question.

### Alternative 1
You can always create a custom `IApiVersionReader` to provide whatever implementation you want. The `IApiVersionSelector` is meant to choose from possible candidates when there is nothing available (e.g. `null`). Choosing something different than what the client asks for is generally a bad idea.

### Alternative 2
If you want to use your own middleware or set the API version requested, you can always do that via the `IApiVersioningFeature`. This is the exact same process that API Versioning uses itself. It will not, however, override values that have been explicitly set.

For example:

```c#
// shortcut for httpContext.Features.Get<IApiVersioningFeature>(), but will never return null
var feature = httpContext.ApiVersioningFeature();

feature.RequestedApiVersion = new ApiVersion( 2, 0 );
```

You'd likely want your middleware to run pretty early in the pipeline.

**Comment by commonsensesoftware** [comment]
Based on the age and idle state of this issue, I suspect you've found a workable solution and has reached its conclusion. If that turns out not to be the case, feel free to reply or reopen in the issue. Thanks.
