### ISSUE TITLE
Get version programmatically in integration tests

### ISSUE THREAD

**Issue by lonix1** [dotnet/aspnet-api-versioning#788]
I'm using ASP.NET Core 5. I've set up my version format as `"'v'VVV"`.

In an integration test, I'm using the `WebApplicationFactory`. To test an endpoint, I'll use:
````cs
var route = $"/api/v${version}/${controller}/${action}";
var response = await client.GetAsync(route);
````

I'd prefer not to hardcode `version`.

Is it possible to get it from the test server? Maybe I can get the api versioning service from the container and get the formatter version from there? Unsure how though.

**Comment by lonix1** [comment]
Wow that is so much more info than I expected. Thank you! :smiley: 

I'm going to wrap all that into something that only runs during testing. I think I'll create a test-only controller that exposes all that detail. That will keep it clean in my production code.

Last question, if you don't mind. During the integration test I do have the `ApiVersion` used by the server, and I know that it has format `"'v'VVV"`. But I don't know how to format that. So I thought to search the test server's `IServiceCollection` for the library's service, and hoped that if I found it I'd be able to use it to format the version to "v0" or "v0.1.0" or whatever. I'm not sure what service this library registers so didn't know what to look for. Is that possible?

If not, I'll stick to the way you described. BTW it would make an excellent addition to the docs, you've explained it so clearly!

**Comment by commonsensesoftware** [comment]
No problem.

To be clear `v` is never part of an **ApiVersion**. **ApiVersion** does support **IFormattable** with custom formatting. The format `'v'VVV` is meant for formatting the _display version_, which is most commonly used in OpenAPI documents. If you're using a numeric format, the values `1.0` and `1` are semantically equivalent. API Versioning, however, will not omit the `0` if originally unspecified. Typically, that only matters for display purposes. `v1.0` and `v1` are exactly the same. Similarly, `[ApiVersion("1.0")]` and `[ApiVersion("1")]` are also the same. If you really, really want to get and use the format, you can get it from `ApiExplorerOptions.GroupNameFormat` by injecting `IOptions<ApiExplorerOptions>`.

I got the impression that the client and server were separated in your test suite, but _maybe_ they are together. If they're together, you can also use the **IApiVersionDescriptionProvider** service (part of the API Explorer extensions) to list all API versions. The collection of API versions reported is flat for the entire application. If your APIs are not symmetrical in versions, then this might not work for because not every reported version will be available for all APIs. This service is mostly used to determine the versions required to produce OpenAPI documents.

Honestly, if you do have references to the server implementation, then the best option is to go through the API Explorer. That is how all OpenAPI documents are generated. By going through that path, you don't need to worry about formatting URLs, API versions, etc. The API Versioning extensions for the API Explorer will automatically collate APIs by their version. If you combine that with the **IApiVersionDescriptionProvider**, you can automate most everything (which was also a considered use case in the original design 😉 ).

Something like:

```c#
// get all these from ID
IOptions<ApiExplorerOptions> options;
IApiVersionDescriptionProvider versionProvider;
IApiDescriptionGroupCollectionProvider groupProvider;

// create a lookup
var groups = groupProvider.ApiDescriptionGroups
                          .Items
                          .ToDictionary(group => group.GroupName, group => group.Items);

// process each group (e.g. [formatted] API version)
foreach (var description in versionProvider.ApiVersionDescriptions)
{
    var apis = groups[description.GroupName];

    foreach (var api in apis)
    {
        var version = api.GetApiVersion();   // versioning extension; if needed
        var deprecated = api.IsDeprecated(); // versioning extension; if needed
        var url = api.RelativePath;

        // TODO: use info
    }
}
```

There's a lot of different ways this _could_ be used. I haven't done it myself, but there is probably some way to match this up with **IHttpClientFactory** so you can use it in a test base class. Something like:

```c#
public class ApiServer : IDisposable
{
    private readonly Lazy<TestServer> server;
    private bool disposed;

    public ApiServer() => server = new Lazy<TestServer>(CreateServer);

    public IServiceProvider Services => Server.Services;

    protected TestServer Server => server.Value;

    public HttpClient CreateClient(string name)
    {
        var factory = Server.Services.GetRequiredService<IHttpClientFactory>();
        var client = factory.Create(name);

        // TODO: the 'magic' here would be extending/replacing the default
        // IHttpClientFactory to apply 'http://localhost/api/v{version}'.
        // this might need more parameters or a 'magic string' such as
        // 'Values-V1', which is probably 'ok' for testing purposes
        client.BaseAddress ??= new Uri("http://localhost");

        return client;
    }

    public HttpMessageHandler CreateHandler() => Server.CreateHandler();

    public void Dispose()
    {
        Dispose(true);
        GC.SuppressFinalize(this);
    }

    protected virtual void Dispose(bool disposing)
    {
        if (disposed)
        {
            return;
        }

        disposed = true;

        if (!disposing)
        {
            return;
        }

        if (server.IsValueCreated)
        {
            server.Value.Dispose();
        }
    }

    protected virtual TestServer CreateServer()
    {
        var builder = WebHost.CreateDefaultBuilder()
                             .ConfigureServices(OnConfigureServices)
                             .UseStartup<Startup>(); // your real or alt startup

        // use TestServer from Microsoft.AspNetCore.TestHost
        return new TestServer(builder);
    }

    private void OnConfigureServices(IServiceCollection services)
    {
        // TODO: configure your services here
    }
}

[CollectionDefinition(nameof(ApiTestCollection))]
public class ApiTestCollection : ICollectionFixture<ApiServer>
{
    // NOTE: this class intentionally has no implementation; Xunit will use this signature
    // to create and manage all tests that use the fixture as a single collection
}

[Collection(nameof(ApiTestCollection))]
public abstract class ApiTest
{
    private readonly string name;

    protected ApiTest(ApiServer server, string name)
    {
        Server = server;
        this.name = name;
    }

    protected ApiServer Server { get; }

    protected HttpClient Client => Server.CreateClient(this.name);
}

// adding API tests are now easy to light up
public class ValuesV1Test : ApiTest
{
    [Fact]
    public Task get_should_return_ok()
    {
        // arrange
        const string url = "values";

        // act
        var response = await Client.GetAsync(url);

        // assert
        response.StatusCode.Should().Be(HttpStatusCode.OK);
    }

    public ValuesTest(ApiServer server) : base(server, "Values-v1") { }
}
```

There is potentially a _Chicken & Egg_ dilemma here if you try to use the API Explorer metadata to configure the **IHttpClientFactory** because they both require DI configurations, but you don't have the metadata (yet) to configure the **IHttpClientFactory**. A way around that would be to create separate **IServiceProvider** to get the metadata and _then_ configure **IHttpClientFactory** (e.g. `services.AddHttpClient("Values-V1")`).  This can be achieved with `services.CreateProvider()` after the minimum set of required services are registered in the test suite. It's gonna hurt the test start up time because it will create and go through some level of duplicate DI twice, but it's only for testing and you only have to do it once per entire run. I think that's a reasonable compromise if you want this type of automation.

That's not an entire solution, but it should lay the ground work for creating fairly generic integration tests. Spinning up a server, even the in-memory **TestServer**, has a **lot** of overhead. You want to reuse it as much as possible. API Versioning uses this approach for its acceptance tests (e.g. the closest thing to integration tests). The time went from ~12 mins to 90 seconds by reusing the same server instance via test fixtures.

Long, overdrawn answer, but hopefully you (and others) may find that useful.

**Comment by lonix1** [comment]
Once again very enlightening... Thank you!

I realize that if I do it the way I described I'll run into problems once my server supports multiple API versions. But I need to get to that point first! :smile:  When I do I'm going to do it the "proper" way as you've described, and expose the version information as an endpoint of its own. The code you supplied is basically a complete solution - I've used it and it works like a charm!

But for anyone like me who just need to get up and running on "v0" and throw down some integration tests, getting the "current api version" is possible using your second bit of code:
````cs
var currentVersion = _webApplicationFactory
  .Services
  .GetRequiredService<IApiVersionDescriptionProvider>()
  .ApiVersionDescriptions
  .Single()          // when you add more versions, this forces test to fail - at that point, redesign!
  .GroupName;        // I used format "'v'VVV" so this gives "v0"

var route = $"/api/{currentVersion}/{controllerName}/{actionName}";
var response = await client.GetAsync(route);
````

Thank you so much for explaining the process. I now have a both an unblocking solution, and a robust solution for when I add the next API version. :+1:
