### ISSUE TITLE
Swashbuckle Integration

### ISSUE THREAD

**Issue by RyanGaudion** [dotnet/aspnet-api-versioning#792]
I am trying to use the Swashbuckle Integration as defined here 'https://github.com/dotnet/aspnet-api-versioning/wiki/Swashbuckle-Integration' for asp.net core. However I get the following error when compiling the example:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'ApiDescription' does not contain a definition for 'IsDeprecated' and no accessible extension method 'IsDeprecated' accepting a first argument of type 'ApiDescription' could be found

I have also tried the example here -https://github.com/dotnet/aspnet-api-versioning/blob/master/samples/aspnetcore/SwaggerSample/SwaggerDefaultValues.cs but get the same error.

What is it that I'm missing?

**Comment by commonsensesoftware** [comment]
One or more of the following must be true:

- You did not reference  [Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer)
- You did not include `using Microsoft.AspNetCore.Mvc.ApiExplorer;` (I'm assuming C#)
- You're using an older library version before `IsDeprecated` was introduced (you didn't say which version you're using)

Hopefully, one of those leads you to the solution; otherwise, I'm happy to help continuing to resolve the issue.

**Comment by RyanGaudion** [comment]
@commonsensesoftware  thank you for your reply. It was the first one. Please can the need for that package be added to the wiki here - [https://github.com/dotnet/aspnet-api-versioning/wiki/Swashbuckle-Integration](https://github.com/dotnet/aspnet-api-versioning/wiki/Swashbuckle-Integration) in order to help others.

**Comment by commonsensesoftware** [comment]
I had hoped it would have been clear from the landing page and example project, but I'm happy to add more documentation to the wiki. Glad that solved your issue. Thanks for the feedback.
