### ISSUE TITLE
UrlHelper with ApiVersionNeutral and AssumeDefaultVersionWhenUnspecified includes version

### ISSUE THREAD

**Issue by fredrikahs** [dotnet/aspnet-api-versioning#798]
Is there any way to not include the version as a query parameter when generating a link for an action that has `ApiVersionNeutral`? `AssumeDefaultVersionWhenUnspecified` is set to true.

For example, this code generates something like https://localhost:5001/redirect?version=1
```csharp
[HttpGet("redirect")]
[ApiVersionNeutral]
public IActionResult Get() => Ok();

[HttpGet("/v{version:apiVersion}/generate")]
[ApiVersion("1")]
[AllowAnonymous]
public IActionResult Generate() => Ok(Url.ActionLink("Get"));

///

services.AddApiVersioning(options => 
{
    options.AssumeDefaultVersionWhenUnspecified = true;
    options.DefaultApiVersion = new ApiVersion(1, 0);
});
```

**Comment by commonsensesoftware** [comment]
This is an interesting question. Since things are flowing from v1 to version-neutral, the route parameter `version` flows through. As there is no matching route parameter `version`, the `IUrlHelper` is appending it as a query string value. API Versioning is **not** adding it to the query string. That is ASP.NET Core's behavior.

The **ApiVersionUrlHelper** only adds the API version as a route value if it is set. I haven't tested it myself, but temporarily clearing the API version should get you the behavior that you want.

```c#
[HttpGet("/v{version:apiVersion}/generate")]
[ApiVersion("1")]
[AllowAnonymous]
public IActionResult Generate()
{
    var feature = HttpContext.Features.Get<IApiVersioningFeature>();
    var rawVersion = feature.RawRequestedApiVersion;
    var version = feature.RequestedApiVersion;

    // force values to their defaults
    feature.RawRequestedApiVersion = default;
    feature.RequestedApiVersion = default;

    var link = Url.ActionLink(nameof(Get));

    // restore the values
    feature.RawRequestedApiVersion = rawVersion;
    feature.RequestedApiVersion = version;

    return Ok(link);
}
```

If you needed to use this in several places, you can wrap it with an extension method like this:

```c#
internal sealed class NoApiVersionScope : IDisposable
{
    private readonly IApiVersioningFeature feature;
    private readonly string? rawVersion;
    private readonly ApiVersion? version;
    private bool disposed;

    public NoApiVersionScope(IApiVersioningFeature feature)
    {
        this.feature = feature;
        rawVersion = feature.RawRequestedApiVersion;
        version = feature.RequestedApiVersion;
    }

    public void Dispose()
    {
        if (disposed)
        {
            return;
        }

        disposed = true;
        feature.RawRequestedApiVersion= rawVersion;
        feature.RequestedApiVersion = version;
    }
}

// option 1
internal static class HttpContextExtensions
{
    public static IDisposable NoApiVersion(this HttpContext context) =>
        new NoApiVersionScope(context.Features.Get<IApiVersioningFeature>());
}

// option 2
internal static class ControllerExtensions
{
    public static TResult WithoutApiVersion<TController, TResult(
        this TController controller, Func<TController, TResult> action)
        where TController : ControllerBase
    {
       var feature = controller.HttpContext.Features.Get<IApiVersioningFeature>();
       using var scope = new NoApiVersionScope(feature);
       return action(controller);
    }
}
```

Now your usage would become something like:

```c#
[HttpGet("/v{version:apiVersion}/generate")]
[ApiVersion("1")]
[AllowAnonymous]
public IActionResult Generate()
{
    using var scope = HttpContext.NoApiVersion();
    Ok(Url.ActionLink(nameof(Get));
}
```

or 

```c#
[HttpGet("/v{version:apiVersion}/generate")]
[ApiVersion("1")]
[AllowAnonymous]
public IActionResult Generate() => Ok(this.WithoutApiVersion(c => c.Url.ActionLink(nameof(Get))));
```

May that get you the results you're hoping for.

**Comment by fredrikahs** [comment]
Too bad there's nothing out of the box. I got around the issue by simply removing the query parameter after generating the url. You missed setting the version and rawVersion to default on the scope but other than that it works great.

Would be nice with an option for always generating urls for neutral actions without the query parameter.

**Comment by commonsensesoftware** [comment]
Glad you got things working _mostly_ the way you want. It's worth investigating some way to improve it in the future, but it's unlikely because there isn't really a way to _understand_ what's on the other end of a link.

I summary of how it works:

| Source | Destination | Comments |
| -------- | ------------ | ------------ |
| Versioned | Versioned | Forwards the requested version |
| Neutral | Neutral | Typically nothing to forward |
| Neutral | Versioned | Version has to be explicitly supplied |
| Versioned | Neutral | Version has to be explicitly removed |

The last case, your case, is the only one that requires some level of wonky workarounds. I'll considering adding some form of this solution to make it easier in the future.

**Comment by commonsensesoftware** [comment]
Starting `6.0` there will be a new, out-of-the-box extension method to support this scenario. It will work like this:

```c#
[HttpGet("/v{version:apiVersion}/generate")]
[ApiVersion("1")]
[AllowAnonymous]
public IActionResult Generate() => Ok(Url.WithoutApiVersion().ActionLink("Get"));
```

This can work for any `IUrlHelper` instance.

Since this question has been answered and you have a current workaround, I'm going to close it out. Hopefully, the new, built-in support will make it easier for people that need this in the future.
