### ISSUE TITLE
Adding method level ApiVersion vs MapToApiVersion

### ISSUE THREAD

**Issue by iqb-dawn** [dotnet/aspnet-api-versioning#799]
Consider we have https://github.com/dotnet/aspnet-api-versioning/blob/e16b579d240574053ebd8e7ee38c8686beaee174/test/Microsoft.AspNet.WebApi.Versioning.Tests/Simulators/OrdersController.cs#L11

```
    [ApiVersion( "2015-11-15" )]
    [ApiVersion( "2016-06-06" )]
    public class OrdersController : ApiController
    {
        [MapToApiVersion( "2015-11-15" )]
        public Task<IHttpActionResult> Get_2015_11_15() => Task.FromResult<IHttpActionResult>( Ok( "Version 2015-11-15" ) );

        [Route( "orders" )]
        [MapToApiVersion( "2016-06-06" )]
        public Task<IHttpActionResult> Get_2016_06_06() => Task.FromResult<IHttpActionResult>( Ok( "Version 2016-06-06" ) );
    }
```

versus,

```
    [ApiVersion( "2015-11-15" )]
    [ApiVersion( "2016-06-06" )]
    public class OrdersController : ApiController
    {
        [ApiVersion( "2015-11-15" )]
        public Task<IHttpActionResult> Get_2015_11_15() => Task.FromResult<IHttpActionResult>( Ok( "Version 2015-11-15" ) );

        [Route( "orders" )]
        [ApiVersion( "2016-06-06" )]
        public Task<IHttpActionResult> Get_2016_06_06() => Task.FromResult<IHttpActionResult>( Ok( "Version 2016-06-06" ) );
    }
```

Are the above 2 same? if yes, when we should use action level `ApiVersion` vs `MapToApiVersion`?

**Comment by iqb-dawn** [comment]
Found this explanation here https://github.com/dotnet/aspnet-api-versioning/issues/784#issuecomment-934886972,

So if I add 3.0,

```
[ApiVersion("1.0")]
[ApiVersion("2.0")]
[ApiVersion("3.0")]
[ApiController]
[Route("[controller]")]
public class OrderController : ControllerBase
{
   [HttpGet("{id}")]
   public IActionResult Get(string id) => Ok(new Order(){ Id = id.ToString() });

   [MapToApiVersion("2.0")]
   [HttpGet("{id:int}")]
   public IActionResult GetV2(int id) => Ok(new Order(){ Id = id });

   [ApiVersion("3.0")]
   [HttpGet("{id:int}")]
   public IActionResult GetV3(int id) => Ok(new Order(){ Id = id });
}
```
Get v1 and v3
GetV2 only v2
GetV3 only v3

Is this correct @commonsensesoftware ?

**Comment by commonsensesoftware** [comment]
The easiest way to describe this is:

- **ApiVersion** : _declares_ an API version implemented by a service/controller
- **MapToApiVersion** : _maps_, but does not _declare_ an API version

Technically, these two attributes are almost the same. In the very early days, there was only `[ApiVersion]`. I ultimately changed it because the difference in meaning by location was not clear. Ensuring that things are _intention-revealing_ has always been an important goal.

Separate controllers and types for each API version is arguably the _cleanest_ division of work. I realized that there are some developers that would not be satisfied by that; especially for small changes. HTTP does not have a concept of method overloading. To support _version interleaving_, there had to be a way to indicate which action should be dispatched for a particular API version. This is exactly what _mapping_ an API version does. Mapping an API version, however, does not _declare_ it as an available API version. It just merely maps it. If you map an action to `[MapToApiVersion("42.0")]` and there is no such API version, nothing happens (e.g. it doesn't match - likely 400 or 404).

In ASP.NET Core, there is no longer a concept of a controller in the routing model. There are only _endpoints_, which correspond to actions. Yes - actions can be defined by methods on a controller, but at the end of the day, there are only endpoints. In this new model, that means that you _should_ be able to declare an API version directly on a specific action. When you do that, any API version information defined at the controller level is ignored. In general, I'm not really sure why you would want to do that, but you can. The most interesting part about this capability, however, is that a specific action can be _version-neutral_. This is very useful for a method in an API that does not change over time such as `DELETE`. This limitation was something that bothered me for  a long time and was one of the key motivating factors to support versioning individual actions. It was a bit difficult to reverse integrate these features back into the old Web API model, but was able to shoehorn it in.

For example:

```c#
[ApiVersion("1.0")]
[ApiVersion("2.0")]
[RoutePrefix("order")]
public class OrderController : ApiController
{
   [Route("{id}")]
   public IHttpActionResult Get(string id) => Ok(new Order(){ Id = id.ToString() });

   // DELETE works the same for any and all API versions
   [ApiVersionNeutral]
   [Route("{int}")]
   public IHttpActionResult Delete(string id) => StatusCode(HttpStatusCode.NoContent);
}
```

To address your mapping question, your assumption isn't quite write. Reiterated with annotations:

```c#
// declares 1.0, 2.0, 3.0 for all actions on the controller
[ApiVersion("1.0")]
[ApiVersion("2.0")]
[ApiVersion("3.0")]
[RoutePrefix("order")]
public class OrderController : ApiController
{
   // implicitly maps to 1.0, 3.0 because there is a specific mapping for 2.0
   [HttpGet]
   [Route("{id}")]
   public IHttpActionResult Get(string id) => Ok(new Order(){ Id = id.ToString() });

   // explicitly maps to 2.0
   [MapToApiVersion("2.0")]
   [HttpGet]   
   [Route("{id:int}")]
   public IHttpActionResult GetV2(int id) => Ok(new Order(){ Id = id });

   // explicitly declares 3.0 and does not consider other controller actions
   [ApiVersion("3.0")]
   [HttpGet]
   [Route("{id:int}")]
   public IHttpActionResult GetV3(int id) => Ok(new Order(){ Id = id });
}
```

I didn't test this myself, but I would expect a request to `GET /order/42?api-version=3.0` to result in a 500. The server blows up because `Get` and `GetV3` are ambiguous. They both _declare_ that they implement `3.0`. `Get` is explicitly declared by the controller and implicitly mapped by the action. `GetV3` also explicitly declares `3.0` at the action level. If you removed `[ApiVersion("3.0")]` from the controller, then I would expect it to work normally.

While mixing and matching this way _is_ supported, hopefully you see how it can get very confusing fast. I don't recommend interleaving this way without a good reason. In fact, I would suggest not interleaving at all so the separation is clear. Very, very small changes may make sense. Adding a single, version-neutral action is probably the only other exception.

I hope that helps clear things up.

**Comment by iqb-dawn** [comment]
Thanks for detailed answer. Why don't you have any documentation in docs.micrososft.com?

**Comment by commonsensesoftware** [comment]
This project isn't part of ASP.NET. I'm not part of the ASP.NET team. In fact, there isn't really even a _team_. It's just one guy - me. I've tried to make the wiki comprehensive.

**Comment by iqb-dawn** [comment]
Great work commonsensesoftware 👏
