### ISSUE TITLE
Using odata 8 with AddVersionedApiExplorer braking the swagger page

### ISSUE THREAD

**Issue by jineshpatel99** [dotnet/aspnet-api-versioning#802]
In my configure services if i add these` services.AddVersionedApiExplorer();`  it will break the swagger and saw us swagger with 

'No operations defined in spec!'

if i comment out this code it works as expected i am not sure why.  any ideas
My configure services
```c#
 public void ConfigureServices(IServiceCollection services)
        {
            services.AddVersionedApiExplorer();
            services.AddControllers()
                .AddOData(opt => opt.Count().Filter().Expand().Select().OrderBy().SetMaxTop(100)
                    .AddRouteComponents("api/management/v2", EdmModelBuilder.GetEdmModelV2())
                    .Conventions.Add(new CustomConvention())
                //.Conventions.Remove(opt.Conventions.First(convention => convention is MetadataRoutingConvention))
                );

            services.AddSwaggerGen(swaggerOptions =>
            {
                swaggerOptions.SwaggerDoc("v2",
                     new OpenApiInfo
                     {
                         Title = "test Management",
                         Description = "This is the Swagger documentation for the test Management API.",
                         Version = Assembly.GetEntryAssembly().GetName().Version.ToString()
                     });

                swaggerOptions.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
                {
                    Name = "Authorization",
                    In = ParameterLocation.Header,
                    Type = SecuritySchemeType.Http,
                    Scheme = "Bearer"
                });

                swaggerOptions.AddSecurityRequirement(new OpenApiSecurityRequirement()
                    {
                        {
                            new OpenApiSecurityScheme
                            {
                                Reference = new OpenApiReference
                                {
                                    Type = ReferenceType.SecurityScheme,
                                    Id = "Bearer"
                                },
                                Scheme = "oauth2",
                                Name = "Bearer",
                                In = ParameterLocation.Header
                            },
                            new List<string>()
                        }
                    });

                swaggerOptions.DocumentFilter<SwaggerDocumentFilter>();

                swaggerOptions.IncludeXmlComments(Path.Combine(AppContext.BaseDirectory, $"{Assembly.GetExecutingAssembly().GetName().Name}.xml"));
            });

            services.AddControllers(options =>
            {
                IEnumerable<ODataOutputFormatter> outputFormatters =
                    options.OutputFormatters.OfType<ODataOutputFormatter>()
                        .Where(formatter => !formatter.SupportedMediaTypes.Any());

                foreach (var outputFormatter in outputFormatters)
                {
                    outputFormatter.SupportedMediaTypes.Add(new MediaTypeHeaderValue("application/odata"));
                }

                IEnumerable<ODataInputFormatter> inputFormatters =
                    options.InputFormatters.OfType<ODataInputFormatter>()
                        .Where(formatter => !formatter.SupportedMediaTypes.Any());

                foreach (var inputFormatter in inputFormatters)
                {
                    inputFormatter.SupportedMediaTypes.Add(new MediaTypeHeaderValue("application/odata"));
                }
            });
            AddFormatters(services);
        }
```

Configure

```c#  public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseSwagger(swaggerOptions =>
            {
                swaggerOptions.PreSerializeFilters.Add
                (
                    (swagger, httpReq) =>
                    {
                        swagger.Servers = new List<OpenApiServer>
                        {
                            new OpenApiServer { Url = $"{httpReq.Scheme}://{httpReq.Host.Value}" }
                        };
                    }
                );
            });

            app.UseSwaggerUI(swaggerUIOptions =>
            {
                swaggerUIOptions.SwaggerEndpoint($"/swagger/v2/swagger.json", $"CM v2");
            });

            app.UseRouting();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }```



Controller
` [ApiVersion("2.0")]
    public class FoldersController : BaseController
    {}`

**Comment by commonsensesoftware** [comment]
From looking at this, it appears that you are **not** using OData with API Versioning. API Versioning does not officially support OData 8.0 - yet. If this is your goal, I'm afraid it's not going to work. OData 8 support is on the roadmap, but it's a rewrite do to fundamental OData changes. I'm finally closer to making that a reality, but it's still a little way out. Stay tuned.

Based on this configuration, it _appears_ that the mere inclusion of OData in any capacity breaks the API Explorer. That is a bit strange because usually all `ODataController` implementations apply `[ApiExplorerSettings(IgnoreApi = true)]`. You may have bypassed or otherwise altered this behavior. Unless something has changed (recently), the OData libraries do **not** support the API Explorer. I've tried to champion it before, but the OData team has made no investment in it. Honestly, it would save me a ton of work and headache if they did. I get the impression that some people use the API Versioning OData support just so they are able to integrate it with the API Explorer and OpenAPI (formerly Swagger).

API Versioning support for OData I'm working on, but I'm neither part of the ASP.NET team nor the OData team (they aren't connected). You'd have to ask the OData team on their repo to formally support the API Explorer, if you need that. There are some features that OData supports to create an OpenAPI document, but they don't integrate seamlessly with OpenAPI generators such as Swashbuckle or NSwag nor do they support comprehensive documentation that the API Versioning extensions have long provided such as documenting query options. Unfortunately, I'm just one guy. If you don't need/want API Explorer support for OData, then you just need to make sure that all of those controller are ignored. The simplest way is to inherit from `ODataController` or apply `[ApiExplorerSettings(IgnoreApi = true)]` to you own base classes. For anything else, you'll likely have to build your own extensions and/or kvetch to the OData team to officially support the feature on their repo.

**Comment by commonsensesoftware** [comment]
I looked at this a bit more. Perhaps I jumped the proverbial gun just a bit. This configuration appears that you might be trying to use _some_ of OData. That question does occasionally come up. I don't have any tests or examples with this configuration. I'm not 100% it will work. I wouldn't be surprised if it did **not** work. There's a few peculiar behaviors with only a partial OData implementation. For example, expressing, capturing, and reporting OData query options to the API Explorer. The existing implementation looks for particular OData connection points to enhance the API Explorer. This is an area I hope to improve in the rewrite.

It's unclear if you have reviewed or followed the API Versioning samples with Swashbuckle. You don't need to explicitly use `swaggerOptions.SwaggerDoc` this way. As demonstrated in the examples, all of API versions and descriptors are collated for you automatically by the API Explorer extensions. I would not recommend deviating from that without just cause.

Aside, but I couldn't help but notice `application/odata`. That is not a real or otherwise registered media type. The OData (JSON) media type is simply `application/json`.  In `4.0`, you could add additional media type parameters such as `application/json; odata.metadata=full`. Beginning in OData `4.01`, the `odata.` prefix is optional (e.g. `application/json; metadata=full`). This configuration also appears to address to the ODataInputFormatter and ODataOutputFormatter which does not override and implement base implementation correctly and causes the API Explorer to blow up (I'm the one that filed that bug). To my knowledge, it still hasn't been fixed. 😞 The recommend options are to either remove these entirely (you should only need them if you use/allow `$format`) or replace them with forked formatter implementations that do the correct thing. I would also suggest using `IPostConfigureOptions<MvcOptions>` as opposed to calling `services.AddControllers` twice. It's clearer IMHO and you don't know what the side effects are of calling it twice, even if it does _"work"_.

**Comment by commonsensesoftware** [comment]
OData 8 nor its OpenAPI implementation is officially supported. Reading this again, I see that this issue originated in the OData repo; specifically OData/AspNetCoreOData#480. The crux of the issue is that you have added the API Explorer extensions for API Versioning, but OData doesn't support API Versioning - yet. I provided a detailed explanation of the problem and possible solutions in the OData issue. Did that work for you? Is this really a configuration you are going to continue pursuing?

The `6.0` release is just around the corner. It will have official support for .NET 6.0, OData 8.0, and the API Explorer extensions you can use for OpenAPI. You can find the latest code and examples [here](../tree/main/examples/AspNetCore/OData/ODataOpenApiExample).

I'm in the process of burning down all the open issues. While strange and uncommon, the scenario you've outlined _should_ be supported. If the official support will resolve the issue, then I don't want to bother trying to put in a fix. I will add additional support going forward to make sure 6.0+ does not unnecessarily remove descriptions that it shouldn't.

**Comment by commonsensesoftware** [comment]
API Versioning 6.0 is now in preview with support for .NET 6.0, OData 8.0, and the API Explorer extensions which can be used for OpenAPI. This bug has also been fixed. If you want to use the API Explorer for non-OData routes only, you can; however, both OData and non-OData endpoints are now fully supported.

Note that there are new packages in `6.0`+. You are likely interested in:

- [Asp.Versioning.OData](https://www.nuget.org/packages/Asp.Versioning.OData)
- [Asp.Versioning.OData.ApiExplorer](https://www.nuget.org/packages/Asp.Versioning.OData.ApiExplorer)

Referencing just **Asp.Versioning.OData.ApiExplorer** will bring in everything. If you really only want API Explorer for non-OData routes, then you'll want:

- [Asp.Versioning.Mvc.ApiExplorer](https://www.nuget.org/packages/Asp.Versioning.Mvc.ApiExplorer)
- [Asp.Versioning.OData](https://www.nuget.org/packages/Asp.Versioning.OData)

Also note that the setup now looks like:

```c#
services.AddApiVersioning()     // Core API Versioning services with support for Minimal APIs
        .AddMvc()               // API versioning extensions for MVC Core
        .AddApiExplorer()       // API version-aware API Explorer extensions
        .AddOData()             // API versioning extensions for OData
        .AddODataApiExplorer(); // API version-aware API Explorer extensions for OData
```

You can find the latest OData examples [here](../tree/main/examples/AspNetCore/OData).

Thanks for reporting this.
