### ISSUE TITLE
Doesn't find api's from libraries

### ISSUE THREAD

**Issue by kwaazaar** [dotnet/aspnet-api-versioning#803]
My solution has a web project with a single controller, but project references to other projects that also contain controllers. All apis work fine and the swagger definition contains all apis.

Now I'm adding `AddApiVersioning` and `AddVersionedApiExplorer` and some other modifications for Swagger and the SwaggerUI only shows the api from the main project. When I inspect the `IApiVersionDescriptionProvider`, I reports only the version as specified on the main project. Same with `IApiDescriptionGroupCollectionProvider`, which also only contains info on the api in the main project. However, apis from the references project still work fine.

This solution is over 400 projects. I tried to create a small reproduction, but that one works exactly how it should.

Do you have any hint on where I can look next?

**Comment by kwaazaar** [comment]
So I was a bit quick to open this issue: turns out that only controllers marked with `[ApiController]` are considered. So this behaviour is different from the non-versioned explorer.

Thanks anyway for a great library :-)

**Comment by commonsensesoftware** [comment]
Your observation is correct; however, I want to clarify that this behavior is controlled by the `IApiControllerFilter` service. The default implementation is an aggregation over multiple, registered `IApiControllerSpecification` (via `services.TryAddEnumerable`). There is a built-in, registered implementation - `ApiBehaviorSpecification` that matches `[ApiController]`. Since these libraries are all about versioning APIs, this is a sensible approach to exclude non-API controllers. Some developers mix API and non-API controllers in the same project. The default _filter_ implementation keeps any controller that _is satisfied by_ the _specification_.  Adding a specification to match controllers from external libraries that may have `[ApiController]` applied is how you can include them.
