### ISSUE TITLE
[Suggestion]Migrate to the aspnetcore

### ISSUE THREAD

**Issue by Varorbc** [dotnet/aspnet-api-versioning#806]
Are there plans to migrate to the aspnetcore repository and version consistent

**Comment by commonsensesoftware** [comment]
There is not.

This repository isn't, nor ever has been, part of the ASP.NET team or framework.  There is no funding or sponsorship. This project is a one-man show - me.

The repo was under the Microsoft OSS while I was an employee because I thought that was the _right_ thing to do. That has changed and I've been working for many months to get it all sorted it out; it's a lot of work. Regardless, I've got just about all the details ironed out. I have an announcement and roadmap drafted up. Expect big announcements this week. You may have already noticed the repo is now under the .NET Foundation GitHub organization.

**Comment by Varorbc** [comment]
#807
