### ISSUE TITLE
Configuration in ASP.NET Core 6

### ISSUE THREAD

**Issue by lonix1** [dotnet/aspnet-api-versioning#819]
I'm upgrading an ASP.NET Core project from v5 to v6. I'm using this library.

The new docs say I should register Swashbuckle like so:
````cs
builder.Services.AddEndpointsApiExplorer();    // what is this?
builder.Services.AddSwaggerGen();
````
That `AddEndpointsApiExplorer` is new to v6. Everything works as expected whether I add it or not.

Given that method's name, I'm assuming it is related / similar to this library. How is it related? Should I use it or skip it?

**Comment by lonix1** [comment]
Cross-post on [StackOverflow](https://stackoverflow.com/q/71932980/9971404).

PS, does someone know how to create a tag on SO for this library? E.g. `asp.net-api-versioning`.

**Comment by commonsensesoftware** [comment]
`AddEndpointsApiExplorer` is for _Minimal APIs_. If you aren't using Swashbuckle with _Minimal APIs_, then it is not necessary. The setup you want to follow is the more traditional [OpenAPI Example](../blob/main/examples/AspNetCore/WebApi/OpenApiExample/Program.cs).

`AddApiExplorer` is added via `AddControllers`, both of which require, at least, MVC Core. `AddEndpointsApiExplorer` creates API Explorer descriptions for basic `Endpoint` defines that come from _Minimal APIs_.

**Comment by commonsensesoftware** [comment]
The tag  [aspnet-api-versioning](https://stackoverflow.com/questions/tagged/aspnet-api-versioning) already exists. I come through there fairly regularly. ;)

**Comment by lonix1** [comment]
Lol, didn't see it... the autocomplete failed me!

**Comment by lonix1** [comment]
Wow there are full examples [here](https://github.com/dotnet/aspnet-api-versioning/tree/main/examples/AspNetCore/WebApi) - never saw them before! Should be linked in docs, so very helpful. Thanks for that link!

**Comment by lonix1** [comment]
Those examples are what I need, thanks... closing! :+1:

**Comment by commonsensesoftware** [comment]
Great! I'm glad that worked out. The wiki and other places should have links, but they problem go back to `ms` (formerly `master`). The project and repo are undergoing a big change. Since you're using the new packages, I presume you've read about it. I'm still held up on code signing. As soon as that is done, then I'll make the `main` branch the default branch. That will help people find the correct examples. It's on my backlog to create a better documentation site than just the wiki. That should help too.

You're assumptions are correct. `Minimal APIs` are a _newer_ way to create very simple and quick APIs, but that in no way invalidates the existing model with controllers. Technically, you can mix the two approaches and it _should_ all still work. I haven't tried it myself nor can I think of why someone would want to do that - but they _can_.

**Comment by lonix1** [comment]
PS we found a way forward on that [SO](https://stackoverflow.com/q/71932980/9971404) question. Seems like the official MS docs some attention. Thanks for putting it in perspective.

**Comment by lonix1** [comment]
Yes, I've read about the imminent changes for this library, I wish you the best of luck! :smiley:
