### ISSUE TITLE
Version format migration strategy

### ISSUE THREAD

**Issue by craigktreasure** [dotnet/aspnet-api-versioning#826]
I'm migrating some Azure Function endpoints to an ASP.NET Core 6 application. The version format we are using in our Azure Function endpoints is `d.d-preview.d` for example, `0.1-preview.0`, which isn't compatible with what `ApiVersion` allows as it doesn't allow '.' characters in the Status portion. We have previously shipped clients that call APIs using that format, so I need to keep some compatibility while I migrate to a supported format (which I agree is the right thing to do). Any suggestions? Could the validation rules be relaxed somehow?

Thanks!

**Comment by craigktreasure** [comment]
Ok. I've resolved this myself. At least for my particular scenario, I was able to extend the `QueryStringApiVersionReader` ([Api Version Reader](https://github.com/dotnet/aspnet-api-versioning/wiki/API-Version-Reader)) to strip the problematic '.' character. Worked like a charm.

On the [Version Format](https://github.com/dotnet/aspnet-api-versioning/wiki/Version-Format), it says "It is possible to customize this behavior for legacy and other non-compliant services, which will be covered in the **Advanced Versioning** topic." However, I wasn't able to find an **Advanced Versioning** section or page.

**Comment by commonsensesoftware** [comment]
In `1.0-5.x`, this was not supported. The `status` component did not allow `.`. Starting `6.0`, this was rewritten in a way that no longer uses regular expressions and has better performance. One of the side effects is that a `.` is now allowed. You can see the new implementation [here](../blob/main/src/Abstractions/src/Asp.Versioning.Abstractions/netstandard2.0/ApiVersion.cs#L42).

Hmm... maybe I goofed and there isn't a section for **Advanced Versioning**. While it has certainly always been possible (e.g. `ApiVersion` is not `sealed`), it has historically be difficult to customize. The primary factors are:

1. Cannot use an interface because operators are not allowed (ex: `new ApiVersion(2.0) >= new ApiVersion(1.0)`)
2. Cannot use a struct because they cannot be extended
3. Parsing as a static method on `ApiVersion`:
    a. You can't override it
    b. You can't provide an alternate return type
    c. The rest of the framework doesn't know when or where to call your implementation

Starting in `6.0`, this has all been refactored. Parsing has now been extracted as `IApiVersionParser` and `ApiVersionParser.Default.Parse` retains the old implementation of `ApiVersion.Parse`. `IApiVersionParser` is registered via DI. In the places where it would get used, this service is resolved to parse `ApiVersion`. This means that you can replace it to change the implementation or extend it.

`ApiVersion.IsValidStatus` stayed a static method because:
1. It's about the value, not parsing
2. Makes `status` have consistent meaning

An `ApiVersion` is neither `System.Version` nor a _Semantic Version_, even though some people try to use them. A status with a `.`, however, was common enough that I thought was reasonable to support.

We're up to _Preview 2_ and _Preview 3_ is just around the corner. If you additional thoughts or options about how to make design and process better (aside from documentation), please. Now is the time for change. 😉

**Comment by craigktreasure** [comment]
I hope you don't mind me rambling a bit. I love the fact that the library has a strong opinion on the format. It makes sense and you've tied it all back to the Microsoft REST API guidelines, which is clearly stated. Having 6.x support the `.` makes sense and will certainly make things easier for me ;). I'm planning to ship in the next few months, so if _Preview 3_ is stable and not to bad to migrate to, i'd certainly love to give it a shot. Significant changes between _Preview 2_ and _Preview 3_? If not, maybe I could tinker with _Preview 2_.

I think some migration strategy could still be useful, but I would totally understand if you said it's not worth it. Once you open the flood gates, you risk devaluing the original goal and stance of the project a bit. But, there is something to be said about supporting services who desire to migrate to the suggested version format to maintain compatibility with their existing clients and to be able to move forward in a standard way. I'm imagining a mechanism to "bless" certain APIs for a legacy "unsupported" version format with the expectation that all other APIs would adhere to the suggested version format. But, i'd expect such a mechanism to be super easy to remove when the time comes and not overly intertwined with the supported configuration. Just a thought.

Either way, i'm a fan. Thanks for the hard work and dedication you've put into the project.

**Comment by commonsensesoftware** [comment]
No problem at all. I take all feedback. Some times it changes things. Some times we agree to disagree. Existing and legacy were always on my mind. Many features and concepts started with my own challenges, legacy included. Once the project was out in the wild, there were definitely a lot more tests of effectiveness against existing designs. Incompatibility with existing API version formats have come up before, but not often. It has come up a far amount of times for net new as well. Customization and extensibility was always a consideration, but seeing what it would take by people willing to put in the effort demonstrated it was less than desirable for the reasons listed above. As an example, some people have asked for  3 (`1.0.0`) or 4 (`1.0.0.0`) part API version. I've always that was strange because build and revision numbers are irrelevant to a HTTP client, but - hey - if you want it... 🤷🏽‍♂️ 

The `AssumeDefaultVersionWhenUnspecified` was **only** ever meant to support backward compatibility. If you turn API versioning, then every API is now versions - even if it's implicit. You shouldn't have to touch every piece of API code to deal with that. Similarly, how do you prevent from breaking existing clients. The whole concept wraps around the idea that you had _some_ unstated version (think _"Initial"_ or maybe even _"V1"_), but now realize that you need versioning. This feature allows all of those original APIs to have whatever defined API version you want from `DefaultApiVersion`, which defaults to `1.0`. Existing clients can _chose_ to specify `1.0` if they know to, but if they don't, then this value will be assumed. There are some other ways this capability can be used, but it's mostly be abused. Clients should **always** explicitly request an API version when possible. A server should **always** use the API version the client asks for or fail if it can't process it.

I understand concerns about previews so I won't try to sell you on anything. I have just as many apprehensions about it as everyone else. Here are the things coming in _Preview 3_:

1. Refactor for API Versioning for _Minimal APIs_ (this will be a breaking change from _Preview 2_)
2. Bug fixes for OData support
3. Code signing

If you aren't using _Minimal APIs_, then things should be stable for you. I don't anymore features planned nor any other known issues to fix. OData support is a bit inflight because it was a complete rewrite - again. ☹️ After _Preview 3_, I _think_ things will be close to Release Candidate. The last hurdle is buttoning up code signing. This is taking much longer than I'd like. If that isn't important to you, then you should be fine. I know it's important to some. I would expect in the worse case scenario the only difference between the final RC and release will be signing.

Hopefully that gives you enough information to make an informed decision.

**Comment by craigktreasure** [comment]
Preview 3 is working great. Thanks!
