### ISSUE TITLE
How would you enable PascalCase for OData 8 in .NET 6 minimal hosting model?

### ISSUE THREAD

**Issue by singhkamall** [dotnet/aspnet-api-versioning#838]
When not using minimal hosting model, this used to work:

```
public void Configure(IApplicationBuilder app, IWebHostEnvironment env, VersionedODataModelBuilder modelBuilder)
{
   ...

        modelBuilder.ModelBuilderFactory = () => new ODataConventionModelBuilder();

   ...
}
```

In order to migrate to minimal hosting model, what would be the corresponding approach to enable PascalCase for OData properties?

**Comment by commonsensesoftware** [comment]
Good question. Sorry for not having all the documentation up - yet. This doesn't seem to be something folks change often so it's not in the examples, but - yes - you can definitely still do it.

You can still request `VersionedODataModelBuilder` through DI and you'll get the same instance as before, but that doesn't give you a concise place to continue configuring it. To address that, it's been included in the `ODataApiVersioningOptions` so that you can achieve the same result.

The following should do the trick:

```c#
var services = builder.Services;

services.AddApiVersioning()
        .AddOData(options => options.ModelBuilder.ModelBuilderFactory = () => new ODataConventionModelBuilder());
```
