### ISSUE TITLE
Multiple [MapToApiVerion] attributes on a route make the method appear multiple times in the generated docs

### ISSUE THREAD

**Issue by simple-nathan** [dotnet/aspnet-api-versioning#845]
Rather than copy/paste a whole bunch of code in our API we are trying to add 2 `[MapToApiVersion()]` attributes and then get the version number from the request `HttpContext.GetRequestedApiVersion()`. This all seems to work fine except the method appears multiple times in the generated documentation. So if we have v2 and v3, then they both appear in the v2 docs and also in the v3 docs. Is what we are trying to do feasible?

**Comment by commonsensesoftware** [comment]
Let me try to confirm what you want to achieve. It's not 100% clear which platform this is, but it looks like it _might_ be Web API.

Consider the following:

```c#
[ApiVersion("1.0"), ApiVersion("2.0")]
[RoutePrefix("values")]
public class ValuesController : ApiController
{
    [HttpGet]
    [MapToApiVersion("1.0")]
    public IHttpActionResult GetV1(ApiVersion version) => Ok(new {message = $"Hello from {version}"});

    [HttpGet]
    [MapToApiVersion("2.0")]
    public IHttpActionResult GetV2(ApiVersion version) => Ok(new {message = $"Hello from {version}"});
}
```

This should produce the URL `http://localhost/values`, which when invoked with `?api-version=1.0` goes to `GetV1` and `?api-version=2.0` goes to `GetV2`. There should only be a single entry documented in each API version.

**Comment by simple-nathan** [comment]
Yes sorry, I should have been clearer. This is a Web API in .NET 6. We are trying to do something like this:

```
        [HttpGet("test")]
        [MapToApiVersion("2")]
        [MapToApiVersion("3")]
        public async Task<ActionResult> TestRoute(int uid)
        {
            var version = HttpContext.GetRequestedApiVersion().MajorVersion;

            if (version == 2)
            {
                // do something
            }
            else if (version == 3)
            {
                // do something else very similar that stops a large chunk of duplicated code
            }

            return Ok();
        }
```

The end result of this is that `TestRoute` V3 action will appear in the V2 docs, and vice versa. What we were hoping would happen is that the action would appear in each docs once only.

**Comment by simple-nathan** [comment]
So in your example, if I went to the docs URL for `v2`, e.g. `http://mydocs.org/v2/` I would only see a single entry for `TestRoute` ? Or your docs URL would not contain the API version number?

**Comment by commonsensesoftware** [comment]
By _docs_, I presume you mean OpenAPI (formerly Swagger). Assuming that is true, then the answer is - yes, provided you're also using the API Versioning API Explorer extensions. The API Explorer extensions collate APIs by their versions. As shown in the [example code](../tree/main/examples/AspNetCore/WebApi/OpenApiExample), this bucketizes each API per group name which is the formatted API version value (ex: `v2`). In fact, you pretty much _have_ to do it that way because OpenAPI doesn't allow duplicate path entries in a single doc. The only way I know around that is to version by URL segment (ex: `/v1`, `/v2`, etc), which I **strongly** discourage. Even if you happen to version that way, the APIs are still collated by their versions. You'd need some custom code to make it one document, but that doesn't sound like what you want.

If you're using Swashbuckle, you can expected a single entry for the same API in two different documents and versions:

- `/swagger/v2/swagger.json` (displayed as `V2`)
  - `/repro/test/{uid}` (maps to `TestRoute`)
- `/swagger/v3/swagger.json` (displayed as `V3`)
  - `/repro/test/{uid}` (maps to `TestRoute`)

**Comment by commonsensesoftware** [comment]
@simple-nathan were you able to solve your problem? While it's true that might have 2 entries for `v2` and `v3` that map to the same implementation method, it's just that - an _implementation detail_. The client/consumer of your API doesn't know they are mapped to same code. As the server, it's your prerogative to change that however you feel as long as you don't break the contract. Two APIs might look identical to the client, but actually have different implementations. At the end of the day, you are documenting your API, not the code behind it. If you end up with identical entries in `v2` and `v3`, that's ok and it doesn't mean that are actually the same.

**Comment by commonsensesoftware** [comment]
This question appears to been answered and I presume resolved so I'm going to close it out. If it's not or you still need additional assistance, I'm happy to provide more guidance or reopen the issue. Thanks.
