### ISSUE TITLE
Should return 400 for AmbiguousApiVersionException instead of 500

### ISSUE THREAD

**Issue by devlie** [dotnet/aspnet-api-versioning#849]
Is there a reason the versioning middleware returns HTTP 500 (server error) when it encounters `AmbiguousApiVersionException` instead of 400 (user error)? Is there a way to configure library to return 400, or must we handle this in our exception handler?

We are using this version:
```xml
<PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="5.0.0" />
```
When there's a request containing two `api-version` params in query string, service would return 500.

```
Microsoft.AspNetCore.Mvc.Versioning.AmbiguousApiVersionException: The following API versions were requested: 2021-06-01-preview, foo. At most, only a single API version may be specified. Please update the intended API version and retry the request.
   at Microsoft.AspNetCore.Mvc.CollectionExtensions.EnsureZeroOrOneApiVersions(ICollection`1 apiVersions)
   at Microsoft.AspNetCore.Mvc.Versioning.QueryStringApiVersionReader.Read(HttpRequest request)
   at Microsoft.AspNetCore.Mvc.Versioning.ApiVersionReader.CombinedApiVersionReader.Read(HttpRequest request)
...
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by commonsensesoftware** [comment]
The middleware never returns 500 directly; however, `AmbiguousApiVersionException` will be thrown any time multiple, different API versions are requested and they are not **exactly** the same (e.g. ambiguous; even semantic equivalence is not allowed). When an unhandled exception occurs, ASP.NET Core propagates that as 500.

The one and only place this should happen is via `IApiVersioningFeature.RawRequestedApiVersion` which can propagate through `IApiVersioningFeature.RequestedApiVersion`. Extension methods such as `GetRequestedApiVersion()` and any other approach ultimately go through `IApIVersioningFeature`. There's no clear path to transition from accessing a property to a HTTP response, which is why an exception is necessary. API Versioning knows where ambiguous API versions _might_ appear,  appropriately handles it, and propagates 400 instead (as seen [here](../blob/ms/src/Microsoft.AspNetCore.Mvc.Versioning/Routing/ApiVersionMatcherPolicy.cs#L254)). I suspect you have some code somewhere that is accessing the value early in the pipeline. By the time the routing system goes through API Versioning and dispatches to your endpoint, it _should_ be impossible to encounter `AmbiguousApiVersionException`. If that's not the case, you'll need to elaborate on your scenario some more.

Why does this happen? The crux of the problem comes down to `IApiVersionFeature.RawRequestedVersion` and the original design of `IApiVersionReader.Read`. Both of these only allow a single, raw API version value to be read. If there are none, then `null` can be used. What should it do if there are multiple? It _shouldn't_ be `null` as that would imply no API version. There's no way to return multiple API versions; hence, `AmbiguousApiVersionException`.

In `5.1.0`, `IApiVersioningFeature` adds `RawRequestedApiVersions` which is a `IReadOnlyList<string>` of all raw API versions. This will always work whether there are 0 or many API versions requested. Starting in `6.0.0`, `IApiVersionReader.Reader` now returns `IReadOnlyList<string>` which supports multiple, raw API versions from a single reader (ex: the query string) as well as composition (ex: the query string and header). Supporting the possibility of multiple API versions end-to-end removed a lot of cases for exception handling (and improves performance). It also gives a clear way to test if there are multiple API version were requested and what the original, raw values were (for debugging and error reporting).

>Whenever Microsoft finally wraps up the [code signing certificate](https://github.com/dotnet-foundation/projects/issues/214), I'll be able to officially publish the `RawRequestedApiVersions` enhancement. 😞 

I hope that helps clear things up.

**Comment by devlie** [comment]
@commonsensesoftware Thanks for the detaild explanation! You were absolutely spot on that there's something reading the API version. We have a metrics middleware that tries to read the API version as the request comes in. Swallowing the exception there allows the rest of the pipeline to properly return 400 to user. Thanks again!
