### ISSUE TITLE
[Question] Programatically redirect to a valid endpoint version when client requests an invalid one.

### ISSUE THREAD

**Issue by zwanderer** [dotnet/aspnet-api-versioning#855]
Sorry if this is not the right place to ask questions. I couldn't find anything related to that in the Wiki page.

What I want to accomplish is if a client requests an invalid version of an endpoint, it redirects to a valid version of the endpoint. Example:

Controller has attributes ApiVersion("2") and ApiVersion("3"). Client inform API version in headers. If he requests version 1 today, it returns a 405. I'd like to redirect him to lowest supported version (2) instead.

**Comment by commonsensesoftware** [comment]
Yes - this is possible to achieve; however, not out of-the-box. By design, the API version requested by the client must match what the server provides. It wouldn't be acceptable if the client asked for `application/json`, but the server arbitrarily decided to send back `application/xml`. Requesting an API version is no different. The API version is really more of a _representation_ (like a media type) than it is a _version_ as most people think of it. It is often assumed by API authors that versions are backward compatible and can continue to be consumed by existing clients. This simple is not true. The only way that can be guaranteed is if you are both the API author (server) and consumer (client). Even then, things can still go awry.

The client knows what to expect and what it's asking for. The server shouldn't make any assumptions about that. It should either serve it or fail it while indicating why it can't serve it. There are numerous ways to _advertise_ to the client when API versions will be sunset. The server _should_ advertise this information, but there's no guarantee the client will observe or honor it.

To be fair, you did ask about a redirect. Most people ask about using a different API version, which is just wrong IMHO. A `308` redirect could be appropriate because the client still has to choose to follow it (which they might not). It's still fragile because the client doesn't know that they are being forwarded to a new version of the API. It's usually better to fail the request and make the client ask for the correct, supported version.

As an alternative, you an flip the behavior on it's head. You could allow the client to send multiple API versions and the server can choose the most appropriate version available. Today, this is only supported when versioning by media type negotiation and, by default, just the highest version is selected. Making this behavior work correctly can be tricky depending on the API's versioning policy. When looking at API versions, the possible candidate routes haven't been evaluated yet so it can be difficult to determine which versions should be considered. Equally challenging is that API versions can come from multiple sources and the default implementation cannot disambiguate between a client asking the most current API version available and a mistake in asking for multiple, ambiguous versions. With the exception of media type parameters, the server will assume the requested versions are ambiguous to error on the side of caution.

Adding some extensions to select a version from multiple requested versions is pretty straight forward. Adding redirect behavior is possible if you hook into the pipeline and look for 400/404/405 requests related versioning.  Checking or changing the error has been a little difficult, but that is being addressed in .NET 7.0. All of the cases depend on your versioning policy, if it's _symmetrical_ across all APIs, then you should be able to perform a redirect fairly easily. If the versions are asymmetrical, it may not be clear which version you can redirect to.

**Comment by zwanderer** [comment]
Just thinking of a different route to solve my problem, is it possible to have an attribute that sets a range of versions? Something like `[ApiVersion(min = "2", max = "3")]`

To clarify what I want to solve, we want to implement versioning on an existing API. It has several controllers that don't change at all, there's only a couple of Controllers that actually need versioning. The first problem is that every time there is a new version of our API, we would have to go through all controllers and add the new version. The second problem is that developers add a new controller but forget to add the ApiVersion attribute. I was thinking of having two constants set globally, so all the controllers that don't need versioning can reference those constants, and then only the controllers that actually need versioning have versions declared manually.

Do you have a suggestion to cover this scenario?

Thanks for the help.

**Comment by commonsensesoftware** [comment]
Ranges are _possible_, but - again - not out-of-the-box. It's not possible to know how you'd want to step. If you're using date-based ranges, then steps are nonsensical. It is reasonably straight forward to create a custom range that is tailored to your specific needs. The [extensions and customizations](../wiki/Extensions-and-Customizations) wiki page has some additional links and information.

_Conventions_ are an approach that you can use apply conventions in a broader sense to many or all controllers. For example, the `VersionByNamespaceConvention` derives the applied `ApiVersion` directly from the namespace of the containing controller namespace. `MyApp.V1.Controllers` would apply `new ApiVersion(1.0)` to all controllers in that namespace. You can find more information in the [API version conventions](../wiki/API-Version-Conventions) topic. API version are always mutually inclusive so you can combine from attributes, built-in conventions, or your own custom conventions. Use caution and discretion when combining different sources or interleaving multiple version on a single controller. It's allowed and supported, but can get confusing and hard to manage if you're not careful.

Using a convention can also help address the issue of forgetting to apply an API version. If you're able to derive this information from namespace, type, configuration, or some other method that might solve your problem. You're not required to use attributes. That is just one of a few ways the version metadata can be applied. It also tends to be one of the easiest to understand when starting out.

**Comment by zwanderer** [comment]
Thanks for the answers, I will research more about extensions.
