### ISSUE TITLE
Net6.0 versioned MVC API incorrectly applying versioning info in SwaggerUI

### ISSUE THREAD

**Issue by thedwillis** [dotnet/aspnet-api-versioning#870]
When following the examples laid out in the docs I have hit an issue re. swagger UI incorrectly asking for a version to be passed as a parameter:
![image](https://user-images.githubusercontent.com/24714701/187917412-2a36729a-83eb-4075-80e2-70a988bd1682.png)

and when the parameter is passed, it doesn't seem to reflect which versions are exposed by the API; the only controller exposed version is 1.0, but the parameter can be set to any number, resulting in a 200 response received.

 I have attached an example bare bones application that reflects this behaviour, I've been struggling with this for hours now and I've tried lots of different ways to resolve it, but the fountain of ideas has definitely run dry.
 
[Versioned.API.zip](https://github.com/dotnet/aspnet-api-versioning/files/9469889/Versioned.API.zip)

**Comment by thedwillis** [comment]
Leaving a solution here for anyone else encountering the same issue, I found I was missing a `.AddMvc()` call between `.AddApiVersioning()` and `.AddApiExplorer(..)`. As I had a call to `AddMvc(...)` later in startup I thought it would be ok, but I'm guessing the order these things occur is critical.

**Comment by commonsensesoftware** [comment]
Thanks for reporting this. I'm going to categorize it as a 🐞 because it is not what you expected. `AddApiExplorer` _should_ call `AddMvc` automatically if you don't. That will eliminate ordering issues, which you are not _supposed_ to have to worry about. This will be fixed in the next patch release.

The example projects should show complete and correct working setups. Please call it out if they are incorrect.
