### ISSUE TITLE
URL Versioning not working as expected in new ASP.Versioning.MVC package

### ISSUE THREAD

**Issue by luismejia-iq** [dotnet/aspnet-api-versioning#874]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

URL versioning is giving me back the following error stating that multiple endpoints match the request.

This is happening when trying to use the new Nuget Package   _**Asp.Versioning.Mvc**_.  Same code works fine when using the previous  _**Microsoft.AspNetCore.Mvc.Versioning**_

Sample repo:  https://github.com/mejialuis28/api-versioning-error

```
Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches: 


ApiVersioning.Controllers.Data2Controller.Get (ApiVersioning)
ApiVersioning.Controllers.DataController.Get (ApiVersioning)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.Select(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.Matching.DataSourceDependentMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

![image](https://user-images.githubusercontent.com/94065317/188735953-3fef43b3-43d0-4ddb-b6c2-97c3a5607944.png)

### Expected Behavior

Should properly route the request to the right controller action associated to the given API version.

### Steps To Reproduce

Here's a sample git repo that has the issue https://github.com/mejialuis28/api-versioning-error

Run the app and try a get request to:

https://localhost:5001/v1/data/
https://localhost:5001/v2/data/

### .NET Version

3.1

**Comment by pinkfloydx33** [comment]
I'm pretty sure you need to call [`AddMvc`](https://github.com/dotnet/aspnet-api-versioning/blob/00c5d3b8f278df5cc0ee5b34405a62d22ffb202e/src/AspNetCore/WebApi/src/Asp.Versioning.Mvc/DependencyInjection/IApiVersioningBuilderExtensions.cs#L30) after `AddApiVersioning`.

I ran into a related (but not the same) issue until I noticed I was missing that line when reviewing the examples.

**Comment by commonsensesoftware** [comment]
@pinkfloydx33 is correct. thank you.

The setup when using controllers should look like:

```c#
public void ConfigureServices(IServiceCollection services)
{
    services.AddControllers();
    services.AddApiVersioning(options => options.ReportApiVersions = true)
            .AddMvc();
}
```

This is now required because _Minimal APIs_ do not require any part of MVC. By calling `AddMvc`, it adds the fundamental bits from MVC (Core), which is needed when using controllers. The repro (thanks BTW) works as expected with this setup.

**Comment by pinkfloydx33** [comment]
It's a bit hard to spot in the examples and I didn't see mention of it in the Readme, wiki nor the Net6 roadmap posting. Perhaps it needs a bit better documentation.

**Comment by luismejia-iq** [comment]
Thanks both @pinkfloydx33 and @commonsensesoftware  for the quick answer.  That indeed was the issue.  

I didn't spot this in the [URL versioning documentation](https://github.com/dotnet/aspnet-api-versioning/wiki/Versioning-via-the-URL-Path) so might be worth updating that piece for the new version.

**Comment by commonsensesoftware** [comment]
Glad you were able to get it working. Updating the wiki is on my list of things to do. Truthfully, I really want to overhaul the entire documentation site. I'm reaching the limit of what is possible with the wiki.

These changes were called out in the original 6.0 Roadmap discussion and they're reiterated in the _breaking changes_ in the `6.0.0-preview.1` release. The most up-to-date documentation is the example projects themselves, which are all current.

**Comment by jayasankai** [comment]
I managed to resolve the issue by adding .AddMvc() to AddApiVersioning() as in bellow.

builder.Services.AddApiVersioning(options => {
    options.ReportApiVersions = true;
    options.DefaultApiVersion = new ApiVersion(1, 0);
    options.AssumeDefaultVersionWhenUnspecified = true;
}).AddMvc();

**Comment by tiger31** [comment]
In my case controller weren't annotated with `[ApiController]`🤦. Everything worked fine until we needed api versioning

**Comment by commonsensesoftware** [comment]
@tiger31 it has been that way ever since _API Conventions_ were introduced (circa ASP.NET Core 3.x), which was also in the older libraries. Before that, there was not a very clear way to distinguish between a UI controller (e.g. usually `Controller`) and an API controller (e.g. usually `ControllerBase`). A controller is a controller and you can use whatever base type you want or even none of those. This information is outline in the wiki under the [Controller Conventions: API Controllers](../wiki/Controller-Conventions#api-controllers) section, but if you think there is something that can bring more clarity, I'll consider it.

The `ApiControllerAttribute` can be applied at the controller or the assembly level. The example projects put it on the assembly so that you only have to do it in one place:

```c#
[assembly: ApiController]
```

This is appropriate if every controller in your application is an API.  Many code examples include it on the controller for clarity.
