### ISSUE TITLE
Add the ability to set an error response format different from ProblemDetails.

### ISSUE THREAD

**Issue by k-soze** [dotnet/aspnet-api-versioning#906]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

In the current version of Asp.Versioning, it is not possible to change the object model of the response body. It's set to ProblemDetails (through the IProblemDetailsFactory service).
In ASP.NET Core, ProblemDetails is set as the default error object model but it is possible to change it.
The idea is to add the ability to change the error response body model.

### Describe the solution you'd like

I think it would be a good idea to create an intermediate context (as it is already done with ProblemDetailsContext in ASP.NET Core).
Not necessarily by using the ProblemDetailsContext already existing but creating another object model that describes the most the characteristics of an API version error.
Then there would be a error response writer that writes the error response body (which would be by default a ProblemDetails).

### Additional context

Here is how I imagine the solution for this feature:
In the existing error endpoints, let's say `AmbiguousApiVersionEndpoint`, we will use 2 services:
- A factory that creates the error context.
- A writer, that writes the error in the response body (and sets the status code.
Here an example of `AmbiguousApiVersionEndpoint`:
```
    private static Task OnExecute( HttpContext context, ILogger logger )
    {
        var errorContextFactory = context.RequestServices.GetRequiredService<IApiVersionErrorContextFactory>();
        var errorContextWriter = context.RequestServices.GetRequiredService<IApiVersionErrorContextWriter>();
        var errorContext = errorContextFactory.CreateForAmbiguousApiVersion( context );
        if ( errorContextWriter.CanWrite( errorContext ) )
        {
            return errorContextWriter.WriteAsync( errorContext );
        }

        return Task.CompletedTask;
    }
```
I've already forked and created a version with these modifications. I can create a pull request if needed.

**Comment by commonsensesoftware** [comment]
Interestingly, this is the second time in as many weeks that someone has asked about this. In days gone by, there was a more generic `IErrorResponseProvider` which generated [a standard error response format](https://github.com/Microsoft/api-guidelines/blob/master/Guidelines.md#710-response-formats) for the Microsoft REST Guidelines (but actually comes from OData). This was supplanted in `6.0` in favor of RFC 7807 (`ProblemDetails`), which is prolific throughout ASP.NET Core now.

Unfortunately, this is changing again in `7.0`, but only a little bit. ASP.NET Core didn't have a way to centralize `ProblemDetails` in .NET 6.0, but in .NET 7.0 it introduced `IProblemDetailsService`. `IProblemDetailsFactory` will, therefore, be removed in `7.0` in favor of this new service. The [error handling](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-7.0&preserve-view=true#problem-details) topic covers everything in detail.

A key goal for custom error responses is not providing multiple, different ways to do it. API Versioning will continue to pivot on whatever ASP.NET Core provides so that things are consistent and well-understood. Gaps will only be filled when absolutely necessary.

As an interesting aside, the new support will require configuring `AddProblemDetails()` otherwise no `ProblemDetails` will be provided.  Creating your own `IProblemDetailsWriter` gives you full control over how a response is written. You can use the `ProblemDetailContext`, but write a completely different response if you want to. In addition, the default implementation will not write `ProblemDetails` if a response body has already been provided. In terms of priority, the last `IProblemDetailsWriter` that indicates `CanWrite` is true will be used. As a library consumer, your writer should be the last one.

**Comment by k-soze** [comment]
Thanks for the quick answer, I guess it's a good point for me if I'm not the only one asking for this feature :)
I was using the `IErrorResponseProvider` in the previous version, it was a good way to write custom responses.
I didn't know that .NET 7 is introducing the `IProblemDetailsService` and the `IProblemDetailsWriter`. That will be much better.
I suppose you're going to use these services in the next version of Asp.Versioning ?
Is it possible, in the v6, to add an equivalent for those services coming in .NET 7 ? that way developers will have the same behavior (in appearance) when migrating from .NET 6 to .NET 7.
I can propose that in a pull request if needed.

**Comment by commonsensesoftware** [comment]
Ah... I knew those people were out there. 😄

`7.0.0-preview.1` is now available with all of these changes and features. Backporting to `6.0` doesn't come without issues. The only thing that makes sense to do is backport `IProblemDetailsWriter`. Even with the same API design, there would be a breaking change in the identity of the type by namespace and/or assembly when moving forward. It might not be horrible, but it's still bad.

I think I would only consider trying to make that functionality work in `6.x` if there are enough people who say they want it and are not moving to .NET 7.  The compatibility issues aside, I also have to balance getting it out and supporting it as an Army of One with a day job. 😉

**Comment by k-soze** [comment]
Ok, thanks ! :)
In the mean time, I'm willl be obliged to make some changes on my side to make that work by replacing some services.
I'll keep watching if there is something new here.

**Comment by commonsensesoftware** [comment]
`7.0.0` has been released. As it relates to this issue, there are no additional changes from the preview. The default error response revolves around `ProblemDetails` using the new `IProblemDetailsService`. If you do **not** include

```c#
builder.Services.AddProblemDetails();
```

in your configuration, then no `ProblemDetails` are written. If you want to change the shape or entire contents of the response, you can register a custom `IProblemDetailsWriter`. You will be provided the current `ProblemDetailsContext` and you can choose to emit whatever you want in the response (e.g. it doesn't _have_ to be `ProblemDetails`).

**Comment by commonsensesoftware** [comment]
A quick summary for anyone that reaches here:

- `IErrorResponseProvider` - was the mechanism used for error responses **before** RFC 7807 (Problem Details) (`< 6.0`)
- `IProblemDetailsFactory` - replaced `IErrorResponseProvider`, but `ProblemDetailsFactory` couldn't be used in _Minimal APIs_ (`= 6.0`)
- `IProblemDetailsService` and `IProblemDetailsWriter` - replaced `IErrorResponseProvider` and `IProblemDetailsFactory` in favor of a custom `IProblemDetailsWriter` (`>= 7.0`)
   -  You **must** opt in with `AddProblemDetails()`, which most people probably want

Apologies for the churn, but I _think_ we've landed in the _right_ place that aligns with what is supported and expected by ASP.NET Core. I'm going to close this out as part of cleaning house because I think we've reached the conclusion. If you run into an issues or find something that cannot met your needs, feel free to reopen the issue or create a new one.
