### ISSUE TITLE
How Can I use DefineApi?

### ISSUE THREAD

**Issue by mehdihadeli** [dotnet/aspnet-api-versioning#907]
Hi,
How can I use `DefineApi` for defining endpoints with versioning support without using `WithApiVersionSet`?
[This](https://github.com/dotnet/aspnet-api-versioning/blob/93bd8dc7582ec14c8ec97997c01cfe297b085e17/examples/AspNetCore/WebApi/MinimalOpenApiExample/Program.cs#L48) is a sample in your code?  
But after add `Asp.Versioning.Http` NuGet package, I don't have access to this extension method (DefineApi).

**Comment by commonsensesoftware** [comment]
The `DefineApi` extension method never made it out of the preview. The ASP.NET team provided strong feedback not to create a unique grouping concept since they were working on their own. I heeded their feedback, but there is a lot of limitations in the ASP.NET Core _Minimal API_ design for .NET 6.0 that makes things kind of awkward to work with. The most up-to-date .NET 6.0 examples are in the [release/6.2](https://github.com/dotnet/aspnet-api-versioning/blob/71d20b3ac5c8485c9a699ea325630c1b893e1a73/examples/AspNetCore/WebApi/MinimalOpenApiExample/Program.cs) branch.

I'm working on the .NET 7.0 implementation which will make use of the new grouping feature a la `MapGroup`. I still think the team doesn't fully understand the landscape of what people want for grouping, but it is what we have - for now. I will be continuing to provide extensive feedback and champion a model that reflects how people configure APIs. While the new `MapGroup` feature isn't exactly what we'd want, it's more _natural_ than how it was before. You can have a look at the .NET 7.0 implementation [here](https://github.com/dotnet/aspnet-api-versioning/blob/1226167cc3e0796d82d49a4769614a0ef1e666b4/examples/AspNetCore/WebApi/MinimalOpenApiExample/Program.cs).

I'm literally working on a release right now. There are some breaking changes that are either behavioral or part of an implementation detail. The .NET 6.0 vs .NET 7.0 implementation should be source code compatible from a consumer's perspective. The first iteration will be a preview just to give people a chance to play with it and discuss before I commit to the official release. I don't expect any more changes aside from possible bug fixes. I try hard to avoid breaking changes, but since this is a major version upgrade, now would be the time. Look for the release later today.

**Comment by mehdihadeli** [comment]
Thanks for your response.
I hope this group feature add in later releases

**Comment by commonsensesoftware** [comment]
Me too. It's far more logical that define an API version, then the APIs in it. The inverse is _unnatural_ IMHO.

**Comment by mehdihadeli** [comment]
> Me too. It's far more logical that define an API version, then the APIs in it. The inverse is _unnatural_ IMHO.

Is it possible, I copy that version code in my .net 7 version manually for using `DefineApi`?

**Comment by commonsensesoftware** [comment]
In the form that `DefineApi` was, I'm not sure it can carry over. However, things are only in preview and now that I have something working, I'm focusing on how to make it better and more streamlined. Stay tuned! 😉
