### ISSUE TITLE
Using RouteGroup in MinimalApi and versioning

### ISSUE THREAD

**Issue by mehdihadeli** [dotnet/aspnet-api-versioning#913]
Hi,
Could we use route group with versioning in minimal api?
For example in [TodoApi example](https://github.com/davidfowl/TodoApi/blob/main/TodoApi/TodoApi.cs#L10) of David Fowler

**Comment by commonsensesoftware** [comment]
If you use [7.0.0-preview.1](https://www.nuget.org/packages/Asp.Versioning.Http/7.0.0-preview.1), then - yes. Some of the necessary changes for API Versioning with _Minimal API_ grouping came late (RC2 I think). I'm a little behind.

Preview 1 should get you what you need. I'm currently working on Preview 2 with some improvements. You should definitely follow the [setup for Preview 1](../blob/5515464b1b7cbead8a26e2b6da4d2015db608372/examples/AspNetCore/WebApi/MinimalOpenApiExample/Program.cs) because it's the only thing published. If you'd like a sneak peek about how things will look for Preview 2, have a look [here](../blob/2e8d692830a0b97f341eed929c66bdb396b57b17/examples/AspNetCore/WebApi/MinimalOpenApiExample/Program.cs). Most of the changes are fixing some bugs and removing some of the _clunkiness_.

The two previews should be source compatible, but there are some shiny new features in Preview 2 that you'll probably want.

**Comment by mehdihadeli** [comment]
@commonsensesoftware I'm working with .Net 7 latest stable version, so is not possible?

**Comment by commonsensesoftware** [comment]
I think you may be misunderstanding me. API Versioning is on a different release cadence that ASP.NET Core itself. The combination is ASP.NET Core on .NET 7 (RTM) plus API Versioning `7.0.0-preview.1` which targets the official release. Does that make sense?

**Comment by mehdihadeli** [comment]
@commonsensesoftware  Oh, sorry that was my misunderstanding about version, let me check with `7.0.0-preview.1` version of `Asp.Versioning.Http` and .Net 7.

**Comment by commonsensesoftware** [comment]
The examples I linked to above will demonstrate how to wire things. They target the official .NET 7 builds for ASP.NET Core. 😄

**Comment by mehdihadeli** [comment]
Ok thanks for helping :)

**Comment by mehdihadeli** [comment]
@commonsensesoftware
