### ISSUE TITLE
Swagger shows wrong OData query options when setting OData query options globally with EnableQuery in the controller.

### ISSUE THREAD

**Issue by SamGuoMsft** [dotnet/aspnet-api-versioning#927]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When setting OData query options globally:
`builder.Services.AddControllers().AddOData(opt => opt.Filter().Expand())`,

The swagger shows correctly with only filter and expand query parameters
![image](https://user-images.githubusercontent.com/40610249/204120333-86338453-1310-4d37-8604-d26ed03c2bd6.png)

But after adding EnableQuery() in the controller, the swagger shows all the odata query parameters, but we already set the settings globally that we only want filter and expand.
![image](https://user-images.githubusercontent.com/40610249/204120375-58afb0d2-2fe3-4ff5-81c5-35cdbd031906.png)

### Expected Behavior

The expected behavior should be the swagger should be same as we only set as global settings.

### .NET Version

7.0.100

**Comment by commonsensesoftware** [comment]
Can you share anything from your setup? This sounds like it's doing exactly what it's supposed to do. `EnableQueryAttribute` is more than an _on_ switch. It enables a bunch of query-related features. If your controller looks anything like this:

```c#
public class TemplateContentController : ODataController
{
    [HttpGet]
    [EnableQuery]  // ← enables all query options at this point
    [Produces( "application/json" )]
    [ProducesResponseType( typeof( ODataValue<IEnumerable<TemplateContent>> ), 200 )]
    public IQueryable<TemplateContent> Get() => Enumerable.Empty<TemplateContent>().AsQueryable();
}
```

then this is the expected behavior. `[EnableQuery]` enables **all** query options on the action. It also supersedes any global settings. The global settings help eliminate decorating the attribute everywhere.

As I recall, the order of precedence is:

1. `[EnableQuery]`
2. _Model Bound_ settings
3. Global settings

The expected behaviors are gray and not well-documented when you start mixing and matching these. While it would seem they should be mutually inclusive, they appear to be exclusive. On one hand, that makes sense as that would allow lower levels to _override_ the settings at higher levels. `[EnableQuery]` by itself does not have any other way to remove or disable specific settings.

**Comment by SamGuoMsft** [comment]
I did some test last night, if global I set only allow expand, when I applied EnableQueryAttribute in the action level without explicitly setting any query options, and try to use filter, I got following exception:
"The query specified in the URI is not valid. The property 'Language' cannot be used in the $filter query option."

Then I changed to [EnableQuery(AllowedQueryOptions=AllowedQueryOptions.Filter)], I still get the same error. Only when I changed the global setting to allow filter, then the filter query started working. So, I think the Global setting limits the query options which service supports, and EnableQuery and Model Bound settings only can choose the query options under the global setting.

**Comment by commonsensesoftware** [comment]
I have feeling there is a litany of OData bugs here. It's not the first time. It's really hard to separate its bugs and behaviors from everything else.

If I do **not** add `[EnableQuery]` and run it _as is_, then `$top` should not be enabled. The behavior I get does correctly omit this from the query options; however, if you just try to run a query manually with `$top=1` or `top=1`, you'll observe the query option is simply ignored (rather than indicating that it's not allowed). I observed similar behaviors with `$skip=1` and `skip=1`; however, if `[EnableQuery]` is present it works, but when it absent, it is simply ignored.

There appears to be OData bugs here that do not validate disable query options (e.g. ignores them) and there is an issue specifically with `$top` where the `MaxTop` value needs to be set globally. Setting it in `[EnableQuery(MaxTop=100)]` appears to have no effect. Now, if I add `SetMaxTop(3)` and add `[EnableQuery(MaxTop=2)]`, then `$top=1` works. If I try `$top=3`, it fails (expectedly) with the max `$top` is `2`, even though the global setting says 3.

Again, these behaviors are super confusing and very poorly documented. I feel like the first step is to lean in on the OData team and get them to properly document the order of evaluation and precedence with different configurations. I'm happy to get something queued up, but the community really needs to chime in to drive progress. Response and resolution to such issues are historically slow.

It's hard for me to _fix_ things if I don't know what the expected behavior even is. I've looked at the OData test suite too and I can't find anything that covers mixing query setting configuration from multiple places. The `$top` case, in particular, has some oddities. I seem to remember that in one case the setting is `int? MaxTop` where `null` is the default and another case it's `int MaxTop` where `0` is the default. These seems to be incongruent.

If you have additional information or insight to share, it is welcome.

**Comment by commonsensesoftware** [comment]
Scrolling through the OData issues, I found bug OData/AspNetCoreOData#695, which coincides with the behavior we've both observed.

I think I may open a separate issue to have the OData team share and document what the expected order of option precedence is, but this looks like a but on the OData side.

**Comment by SamGuoMsft** [comment]
Sure, please paste the bug link here when you open in OData github, then we can close this issue.

**Comment by commonsensesoftware** [comment]
Honestly, I've been meaning to get clarity on precedence for a long time. Hopefully, it will come sooner rather than later. Tracking it with: OData/AspNetCoreOData#754

**Comment by commonsensesoftware** [comment]
It turns out the precedence is documented and tested. I randomly stumbled across the link:

https://learn.microsoft.com/en-us/odata/webapi/modelbound-attribute#overall-query-setting-precedence

As it relates to this issue, the explored query options is correct. The problem with `$top` is a bug in OData. The workaround appears to be `SetMaxTop` to any value and then you can use `[EnableQuery]` to provide a more restrictive `MaxTop`; if you want to.

**Comment by SamGuoMsft** [comment]
@commonsensesoftware, from the document, it said "Query settings can be placed in many places, with the following precedence from lowest to highest: System Default(not query-able by default), Global Configuration, Model Bound Attribute, Fluent API."

But it didn't talk about EnableQueryAttribute, Does EnableQueryAttribute are working separately, so the query violent one of them (Global configuration and EnableQuery in my sample) will fail the request? If yes, then EnableQuery is not included in the precedence order.

**Comment by commonsensesoftware** [comment]
Yeah, the text is poorly written and has grammatical mistakes. You're correct that `[EnableQuery]` isn't explicitly listed in order, but it's listed. There are linked tests. I'm not sure if that shows the combination you're looking for. `$skip` was an easier one to prove. If you don't add globally or via model bound attributes, but you add `[EnableQuery]` it will work. If you don't, the `$skip` simply doesn't work. That _feels_ wrong too because I would think that disallowed query options would return a client error as is the case with most other options.

**Comment by commonsensesoftware** [comment]
I haven't tried it E2E, but something like this should work:

Provide some way to define allowed properties. Attributes are _one_ way.

```c#
[AttributeUsage( AttributeTargets.Method, AllowMultiple = false, Inherited = true )]
internal sealed class AllowedPropertiesAttribute : Attribute
{
   public AllowedPropertiesAttribute( string property, params string[] otherProperties )
   {
      var properties = new string[otherProperties.Length + 1];

      properties[0] = property;

      if ( otherProperties.Length > 0 )
      {
         Array.Copy( otherProperties, 0, properties, 1, otherProperties.Length );
      }

      Properties = properties;
   }

   public IReadOnlyList Properties { get; }
}
```

There's a few ways this might be used. Something like:

```c#
[EnableQuery(AllowedQueryOptions = AllowQueryOptions.Expand)]
[AllowedProperties("customer", "lineItems")]
public IActionResult Get(int id) => Ok();
```

Now you can create a convention that looks like:

```c#
internal sealed class AllowedPropertiesConvention : IODataQueryOptionsConvention
{
   private readonly ODataQueryOptionSettings settings;

   public AllowedPropertiesConvention(
      IODataQueryOptionDescriptionProvider descriptionProvider,
      IModelMetadataProvider modelMetadataProvider,
      ODataOptions option )
   {
      settings = new()
      {
         NoDollarPrefix = true,
         DescriptionProvider = descriptionProvider,
         DefaultQuerySettings = options.QuerySettings,
         ModelMetadataProvider = modelMetadataProvider,
      }
   }

   public void ApplyTo( ApiDescription apiDescription )
   {
      // applying the convention as endpoint metadata is probably a better way to do this
      // but it requires more initial setup
      var method = ((ControllerActionDescriptor) apiDescription.ActionDescriptor).MethodInfo;
      var enableQuery = method.GetCustomAttribute<EnableQueryAttribute>();
      var allowed = method.GetCustomAttribute<AllowedPropertiesAttribute>();

      if ( enableQuery == null || allowed == null )
      {
         return;
      }

      var queryOption = enableQuery.AllowedQueryOptions;

      switch ( enableQuery.AllowedQueryOptions )
      {
         case AllowedQueryOptions.Expand:
         case AllowedQueryOptions.Filter:
            break;
         default:
            return;
      }

      var context = new ODataQueryOptionDescriptionContext( apiDescription );

      for ( var i = 0; i < allowed.Properties.Count; i++ )
      {
         context.AllowedProperties.Add( allowed.Properites[i] );
      }

      var name = ( settings.NoDollarPrefix ? string.Empty : "$" ) +
                 option.ToString().ToLowerInvariant();
      var type = typeof( string );
      var description = settings.DescriptionProvider.Describe( queryOption, context );
      var parameter = new ApiParameterDescription()
      {
            IsRequired = false,
            ModelMetadata = new ODataQueryOptionModelMetadata(
                settings.ModelMetadataProvider,
                type,
                description ),
            Name = name,
            ParameterDescriptor = new()
            {
                Name = name,
                ParameterType = type,
            },
            Source = BindingSource.Query,
            Type = type,
        };

      apiDescription.Parameters.Add( parameter );
   }
}
```

Finally, since DI is needed to get some of the services to build out the convention, we need `IConfigureOptions<T>`:

```c#
public sealed class ODataConventionSetup : IConfigureOptions<ODataApiExplorerOptions>
{
   private readonly IModelMetadataProvider modelMetadataProvider;
   private readonly IOptions<ODataOptions> odataOptions;

   public ODataConventionSetup(
      IModelMetadataProvider modelMetadataProvider,
      IOptions<ODataOptions> odataOptions )
   {
      this.modelMetadataProvider = modelMetadataProvider;
      this.odataOptions = odataOptions;
   }

   public void Configure( ODataApiExplorerOptions options )
   {
      var convention = new AllowedPropertiesConvention(
         options.DescriptionProvider,
         modelMetadataProvider,
         odataOptions );

      options.QueryOptions.Add( convention );
   }
}
```

This might seem like a lot of ceremony, but the challenge is trying to add a convention where no convention exists. As I mentioned the existing functionality for the fluent conventions API is to have parity with `ODataQuerySettings` and `ODataValidationSettings`. Neither of these have a way to specify the properties allowed with `$expand` or `$filter`. I'm not opposed to supporting it as an enhancement, but it's not there today.

Another possible option is to use the current, albeit limited, support for `$expand` and `$filter` conventions and update the description after the parameter is added with the additional properties. Of course, you could go down the Swashbuckle or OpenAPI extensions, but you'll have many of the same challenges.

Hopefully that give you a few ideas.

**Comment by SamGuoMsft** [comment]
> Yeah, the text is poorly written and has grammatical mistakes. You're correct that `[EnableQuery]` isn't explicitly listed in order, but it's listed. There are linked tests. I'm not sure if that shows the combination you're looking for. `$skip` was an easier one to prove. If you don't add globally or via model bound attributes, but you add `[EnableQuery]` it will work. If you don't, the `$skip` simply doesn't work. That _feels_ wrong too because I would think that disallowed query options would return a client error as is the case with most other options.

Funny thing if I don't have global setting, and only apply [EnableQuery(AllowedQueryOptions = AllowedQueryOptions.Expand | AllowedQueryOptions.Filter)] into the action, the filter and expand will not work, but the swagger starts show expand and filter query parameters :). I guess at this moment, I will add them in both global and enable query to make sure both swagger and functionally working :)

**Comment by commonsensesoftware** [comment]
There's definitely some weird stuff having in OData, but I think it's outside of my control here. I _believe_ the order of processing is correct. I don't think I can solve the other OData oddities though. Is there more for us to do here?

**Comment by commonsensesoftware** [comment]
@SamGuoMsft I'm pretty sure I understand why you are seeing incongruence with `[EnableQuery`. I've outlined it in more detail in OData/AspNetCoreOData#695. Long story short, _Model Bound_ Settings take precedence over `[EnableQuery]`. If you have **any** model bound settings defined by attribute or convention, then execution short-circuits. This is because `EnableQueryAttribute` is an `IActionFilter` which runs **after** the validation occurs. The only exception is global settings because they are realized a different way.

I _could_ more strictly enforce that query option discovery to adhere to how it will be realized. I'm pretty sure I can make it match. Unfortunately, I don't think it will really solve the crux to the problem because:

1. The query options will be missing, but you won't know why
   a. Which will drive people to file bugs as the OData behavior is confusing (which they already do)
2. If the behavior is changed or fixed, then things break

I'm open to revisiting this in the future, but for now, I don't know there is more to do on this issue. Is there other reason to leave this open?

**Comment by SamGuoMsft** [comment]
@commonsensesoftware, let's don't change anything, I was looking at the code, if we use model bound settings, the settings will be set under ModelBoundQuerySettings, and validation will check this ModelBoundQuerySettings first, then check global settings. I chatted with Sam Xu, the idea order should be  Model setting > Enable Querable > Global Setting, but seems the implementation is not good. He said he will find some time to fix in their end in the future. I think we don't need to change anything until OData library has the fix. So close this issue.
