### ISSUE TITLE
Endpoints with no version disappear when using `AddMvc` method

### ISSUE THREAD

**Issue by jopmiddelkamp** [dotnet/aspnet-api-versioning#942]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When chaining the `.AddMvc()` onto `AddApiVersioning()` the endpoints without `[ApiVersion]` attribute are not found anymore.

Example repo:
https://github.com/jopmiddelkamp/aspnet-api-versioning-6.3.1-bug

### Expected Behavior

I would expect the routes without the version to still be available. 

So in the example repo I would `/.well-known/example.toml` to still be available when chaining `.AddMvc()` onto `.AddApiVersioning()`.

### Steps To Reproduce

Fork my example repo:
https://github.com/jopmiddelkamp/aspnet-api-versioning-6.3.1-bug

And chain `.AddApiVersioning()` with `.AddMvc()`.

### .NET Version

6.0.400

### Anything else?

- ASP.NET Core version: 6

**Comment by commonsensesoftware** [comment]
This behavior is expected and is by design. Once you opt into API Versioning, you cannot have _unversioned_ APIs; at least, not out of the box. Attributes are just one method of applying API versioning metadata. They can be applied by convention as well.

Barring no other API version information, any controller with `[ApiController]` will have the API version `ApiVersioningOptions.DefaultApiVersion`. This property has the default value of `ApiVersion.Default`, which equals `1.0`. Any other application of metadata by attribute or convention invalidates this behavior. This makes it possible to sunset this convention-based API version on a controller. This behavior has always existed and is meant to ease the process of _grandfathering_ in existing services. If you had tens or even hundreds of controllers, you wouldn't want to have suddenly apply the `[ApiVersion]` attribute to all of them. It's not just inconvenient, it would result in a lot of source control churn too.

There are several ways to avoid this behavior:

1. If the controller does not care about a version - ever, then you can apply `[ApiVersionNeutral]`
    a. This _could_ cause future problems if the API ever needs to become explicitly versioned
2. Not applying `[ApiController]` will result in API Versioning ignoring the controller
    a. This behavior is driven by the `IApiControllerFilter` and `IApiControllerSpecification`
    b. The `ApiBehaviorSpecification` can be replaced with your own implementation that provides custom matching
    c. The entire filter service can be replaced, but that is usually unnecessary; it just matches any specification given to it

>**Aside:** Setting `AssumeDefaultVersionWhenUnspecified = true` is unlikely to do what you think it will do. Since you are versioning by URL segment (e.g. unRESTful), it is impossible to have a default value in the middle of the route template. It would be no different than having a default in `order/{id}/items`; `{id}` **must** be specified to match. The one and only way this will ever come into play using a URL segment is if you use _double route registration_; e.g. `v{version:apiVersion}/weather` and `weather`. The route without the explicit route parameter will _assume_ `DefaultApiVersion` as its version unless you change `ApiVersionSelector` as well.

**Comment by jopmiddelkamp** [comment]
Thanks for your quick reply @commonsensesoftware! I think in our case the `[ApiVersionNeutral]` seems to be the way to go. Sorry to have bothered you with this!

**Comment by commonsensesoftware** [comment]
No bother at all. This is the one-stop shop for all things API Versioning.

Naming is a tricky thing. API _version-neutral_ doesn't mean _ignore_ API version, though you can certainly interpret and use it that way. What it really means is _"I accept any and all API versions, including none at all"_.  This behavior became ever-so-slightly more constrained starting in `6.0`+ (due to routing changes). The statement still holds true, but if client does specify an API version to a version-neutral endpoint, it must be one that exists in the app as opposed to just any arbitrary version. There's a technical reason behind it, but it's also a sensical behavior.

I've seen teams use it the past where a client forwarded their own API version that wasn't expected or known to the API. It was months before they realized this was happening. They eventually decided that _version-neutral_ was not really what they wanted and reverted to explicit API versions. Suddenly, they saw a huge uptick in `400` responses because the requested API version was unsupported (or rather nonexistent). Being _version-neutral_ is certainly needed and useful in the right situation, just be sure it's really want you want. APIs for health probes are common use case. These APIs **never** change over time.

**Comment by Lonli-Lokli** [comment]
@commonsensesoftware What if the only controller I have is OData? Does [ApiController] still needs to be applied in order to be visible in OpenApi schema?

The reason why I am asking it here because I am trying to follow your example for 6.4 version but still Schem is empty, while I have single IModelConfiguration for some ODataController

**Comment by commonsensesoftware** [comment]
@Lonli-Lokli The short answer is - no - `[ApiController]` does not have to be applied; however, based on your other questions, I think there may be a bit more explanation.

A controller is a controller, but we're only interested in versioning API controllers. If you happen to mix API versioning with UI controllers or Razor pages, we don't want to version those. API Versioning introduced `IApiControllerFilter` to solve this (years ago) and the default implementation takes a sequence of `IApiControllerSpecification` instances to implement it. There are two built-in specifications. The first specification matches any controller that applies `[ApiController]`. This is the most natural approach and there really isn't anything else to pivot off of. You _could_ use `Controller` instead of `ControllerBase` if you wanted to and that would be valid. The second specification matches any controller that uses OData; specifically, that has `[ODataAttributeRouting]`, which `ODataController` does.

There is never really a place where `IModelConfiguration` makes a difference. In the full OData stack, it is possible that your `IModelConfiguration` indicates that a particular API version and/or route prefix should not be part of the EDM and that would result in it being omitted. However, if you are using _some_ OData, then the EDM has no effect. A vanilla controller that uses OData query capabilities without being fully OData-compliant should expect to follow the rules of any other API controller, which requires it to have `[ApiController]` applied. OData-compliant controllers do not have this requirement.

If you can provide some additional context or even a repro, I can help flush out where things are misaligned.
