### ISSUE TITLE
Question: UnsupportedApiVersionStatusCode with MediaType-based versioning.

### ISSUE THREAD

**Issue by aremes** [dotnet/aspnet-api-versioning#956]
It seems like this setting is not supported when using media-type parameters for versioning. It always returns a 406 (Not Acceptable) instead of the configured status code. Is this correct? Or am I possibly doing something wrong?

**Comment by aremes** [comment]
The documentation for this feature: https://github.com/dotnet/aspnet-api-versioning/wiki/API-Versioning-Options#unsupported-api-version-status-code
states that it does not support versioning by URL segment (which will always return 404). If MediaType versioning always returns 406, may i suggest adding a second note pointing this out?

**Comment by commonsensesoftware** [comment]
I'll have to dig in again and make sure this is, in fact, true. I _think_ you are correct. To be complete clear, it's not _always_ `406`. You could also get `415`. That will depend on whether there is a body in the request. 

`400` vs `404` has long been a gray area that people have different opinions on and it was previously a PITA to customize, which is why this option was added. I guess didn't occur to me that this _could_ apply to versioning by media type since the behaviors are the exact same even without versioning. Technically, I don't believe ASP.NET Core supports `406` because it doesn't know if the requested media type can be negotiated until after it starts writing the response and then it always uses `415`, which - honestly - feels _wrong_ if it's a `GET` request. API versioning can short-circuit the logic by API version much earlier in the pipeline can choose `406` or `415` appropriately.

**Comment by commonsensesoftware** [comment]
It does appear that `UnsupportedApiVersionStatusCode` is not honored for media type negotiation, although that does feel like the way that it _should_ be. At this point in time, I'm not inclined to change it, but I did update the remarks in the documentation to elaborate further. Good call out.

**Comment by aremes** [comment]
Thanks. I agree with you that this is perfectly justifyable behavior. Thanks for updating the docs! :)
