### ISSUE TITLE
Combining CurrentImplementationApiVersionSelector and VersionByNamespaceConvention fails to resolve current version.

### ISSUE THREAD

**Issue by aremes** [dotnet/aspnet-api-versioning#957]
I have configured the system to use
* MediaTypeApiVersionReader
* CurrentImplementationApiVersionSelector
* VersionByNamespaceConvention.

I have put a controller SomeController.cs with /someendpoint under Controllers.V3_9

Calling GET /someendpoint without an api-version parameter in the mediatype returns 406. Explicitly calling it with api-version=3.9 works, so VersionByNamespace seems to do its job.

I've switched to QueryStringApiVersionReader and added ProblemDetails and found out that - for some reason - without a version parameter, it looks for version 1.0. Is there something i'm missing? or do CurrentImplementationApiVersionSelector and VersionByNamespaceConvention not play well together?

**Comment by commonsensesoftware** [comment]
Are you able to share more of your setup and controller (just the skeleton)? The metadata is computed upfront so there isn't any chance of things not working together.  What I speculate is happening is that a route is being matched that doesn't have the version metadata you expect; perhaps none at all. By design, you can't have an _unversioned_ API after you opt in. If no other information is available, then the API version will fall back to `ApiVersioningOptions.DefaultApiVersion`, which defaults to `1.0` is not otherwise configured. If `CurrentImplementationApiVersionSelector` has nothing else to select from, it will chose this value. With a little more information, I can provide a more definitive answer.

**Comment by commonsensesoftware** [comment]
Was there any additional information or context that you can share? Did you ever solve the issue?

**Comment by aremes** [comment]
Unfortunately, no.Long story short: we're doing a major refactoring of an existing service in which we previously had implemented MediaType-based Versioning ourselves. We wanted to switch to this Library now to save code/time, but as it turned out, configuring it to do exactly what we wanted ended up being more code/work than just cleaning up our previous solution (using a custom EndpointSelector implementation). I'll close this issue though. Seems like its somewhat of a unicorn-case ;)
