### ISSUE TITLE
Add support for MVC Areas

### ISSUE THREAD

**Issue by M144-Coder** [dotnet/aspnet-api-versioning#958]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

We have an Asp.NET Core web application structured into seperate areas web dashboard which contains Razor pages and different area for web api. The problem is that Api versioning isn't supprted with Areas although apis can be used with areas and it's officially supported on the asp.net core using methods like MapAreaControllerRoute and using the Area attribute on the controller.

### Describe the solution you'd like

Adding support for api versioning with areas using extension method like MapAreaControllerRoute for ex: MapVersionedAreaControllerRoute.

**Comment by commonsensesoftware** [comment]
I'm not sure what you mean by:

>The problem is that Api versioning isn't supprted with Areas

In what way?

API Versioning doesn't care if your controller is an area. Collation by area is a possible scenario, but it is not intrinsically supported. Combining versioned APIs and UIs in the application is supported, but it doesn't seem to be super common.

If you can explain a bit more about what you want to achieve and what is preventing that from happening, I can probably help flush out how to make it work. Samples of basic setup or a repro project would be quite beneficial as well.

**Comment by M144-Coder** [comment]
Hello @commonsensesoftware. Thsnks for the reply.

Please check this [sample project](https://github.com/M144-Coder/ApiVersioningExample)

When I make a request to this url using postman [](https://localhost:7257/Clients/Account/Get?api-version=2) I always get this exception back:

```
Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches: 

ApiVersioningExample.Areas.Clients.Controllers.AccountController.Get (ApiVersioningExample)
ApiVersioningExample.Areas.Clients.Controllers.Account2Controller.Get (ApiVersioningExample)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

```

**Comment by commonsensesoftware** [comment]
Thanks for the repro. I'll take a 👀

**Comment by commonsensesoftware** [comment]
The problem is two-fold. First and foremost, you did not call `AddMvc()` on the `IApiVersioningBuilder`, which is required in `6.0`+. Without that, only the basic services for _Minimal APIs_ are added. The second problem is that your API controllers are not marked as such.

Most API authors that need/want API versioning do not mix and match API controllers and UI controllers (or code) in the same solution. If you control both sides, do you really need versioning? Maybe. Using both is a supported scenario, but there are some things to note. Before the days of Razor Pages, there were only controllers. Fundamentally, there is almost no different between `ControllerBase` and `Controller`. You don't even need those types to create a _controller_. A controller is just a controller. This is problematic if you mix UI controllers with API controllers. How can you tell the difference? Most people don't want the UI controllers to be versioned (but in rare cases they do 🤷🏽).

Many years back, the `IApiControllerFilter` and `IApiControllerSpecification` services were added to address this ambiguity. When the _API Behaviors_ feature was released, you opt in using the `[ApiController]` attribute. This presents a simple, straight forward specification to determine which controllers should be considered APIs. There is a built-in specification for it and it's registered by default. Your controllers do not have `[ApiController]`, therefore, they are filtered out and are not considered by API Versioning. That is why you get ambiguous matches. API controllers normally use `ControllerBase` as the base class, but you can use `Controller` if you really want to.

You basically have two options...

### Option 1

Apply `[ApiController]` to your API controllers.

```c#
// add api versioning with support for mvc (core)
services.AddApiVersioning(options => options.AssumeDefaultVersionWhenUnspecified = true)
        .AddMvc(); // this is NOT the same as 'services.AddMvc()`
```

```c#
[ApiController]
[Area("Clients")]
public class AccountController : Controller
{
    [HttpGet]
    [AllowAnonymous]
    public IActionResult Get() => Ok("Version 1");
}
```

### Option 2

Replace the default `IApiControllerFilter` to perform no filtering. Technically, this would require specifying an API version for UI controllers, but since you are using Razor Pages they are not controllers and will be ignored.

```c#
// use built-in filter that does no filtering
services.AddTransient<IApiControllerFilter, NoControllerFilter>();

// add api versioning with support for mvc (core)
services.AddApiVersioning(options => options.AssumeDefaultVersionWhenUnspecified = true)
        .AddMvc(); // this is NOT the same as 'services.AddMvc()`
```

Chose either of those setups and things will begin to work as expected. 😉

**Comment by M144-Coder** [comment]
Thanks for the detailed and well explained answer.

We aren't using controllers for UI, instead Razor pages are used for UI and versioned Controllers are for API only.

The problem with using ApiControllerAttribute is that I must add Route attribute to each controller and conventional routing can't be used, please check this question on [Stack Overflow](https://stackoverflow.com/questions/60205552/conventional-routing-in-asp-net-core-api).

**Comment by commonsensesoftware** [comment]
Oh, right. Gosh, it's been so long since I've seen anyone use convention-based routing, I forgot about that.

Just go with **Option 2** then. If the `NoControllerFilter` doesn't work for you, you can replace it with your own implementation. You also have the option to add a new `IApiControllerSpecification`. The `DefaultApiControllerFilter` implementation just takes a sequence of registered `IApiControllerSpecification` instances and applies the filter by evaluating them in sequence.

**Comment by M144-Coder** [comment]
Conventional routing is way better than attribute routing specially in large projects where there is tens or hundreds of controllers and a lot of razor pages organized into separate areas folders, instead of setting route attribute on each controller seperately we can with conventinal routing get that done in a few line of codes.

I have tried option 2 and it's working. Thanks for the answer.
