### ISSUE TITLE
ArgumentNullException from Microsoft.AspNetCore.Mvc.HttpContextExtensions.GetRequestedApiVersion

### ISSUE THREAD

**Issue by smithago** [dotnet/aspnet-api-versioning#976]
Asp.net core web app, 

below code throws null ref for requests(https://localhost:63838/health/check) with no version
version = _httpContextAccessor.HttpContext?.GetRequestedApiVersion()?.ToString();  

Code reference
https://github.com/microsoft/dicom-server/blob/main/src/Microsoft.Health.Dicom.Api/Logging/TelemetryInitializer.cs#L41

Call stack of error
 at System.ThrowHelper.Throw(String paramName)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Mvc.Versioning.ApiVersioningFeature.get_RawRequestedApiVersion()
   at Microsoft.AspNetCore.Mvc.Versioning.ApiVersioningFeature.get_RequestedApiVersion()
   at Microsoft.AspNetCore.Mvc.HttpContextExtensions.GetRequestedApiVersion(HttpContext context)
   at Microsoft.Health.Dicom.Api.Logging.TelemetryInitializer.AddApiVersionColumn(ITelemetry telemetry) in C:\repos\dicom-server\src\Microsoft.Health.Dicom.Api\Logging\TelemetryInitializer.cs:line 44

**Comment by commonsensesoftware** [comment]
Do you actually have UI controllers with versioning applied? I did not see that. It's seemingly rare, but some people actually want that.

`UseApiBehavior` was a simple, backward-compatibility flag to disable controller filtering. Before ASP.NET Core 2.1, there was no way to distinguish between an API controller and a UI controller. Once `[ApiController]` was introduced, there was a clear way to determine which controllers are for APIs and which are for the UI, if you are mixing and matching. This is facilitated by the `IApiControllerFilter` service, whose default implementation accepts a collection of `IApiControllerSpecification` instances. There are 2 specifications (in 2 different packages): one that looks for `ApiControllerAttribute` and one that looks for `ODataAttributeRoutingAttribute`. When the filter executes, any controllers that do not meet one or more specifications is excluded from API versioning. This is a breaking change for anyone that wanted to use API Versioning with UI controllers. `UseApiBehavior = false` was a very simple way to opt out of all filtering. This option sat in there for a long time, but starting in `6.0`, there was really no reason to preserve it. If you need to retain this capability, there is an out-of-the-box implementation to meet that requirement - `NoControllerFilter`, which applies no filtering. There is no state and the filter is only called once during initialization so there is no reason to keep it in memory (e.g. singleton).

`IControllerConvention` operates on a controller, but the core library supports _Minimal APIs_ where there are no controllers. _Conventions_ are still supported, but the configuration has been moved to a new library with a slightly different configuration.

Based on your current code, the new setup should be:

```c#
// equivalent to the old ApiVersioningOptions.UseApiBehavior = false
// note: if you don't have any UI controllers, this is unnecessary
services.Replace(ServiceDescriptor.Transient<IApiControllerFilter, NoControllerFilter>());

services.AddApiVersioning(options =>
        {
            options.ApiVersionReader = new UrlSegmentApiVersionReader();
            options.AssumeDefaultVersionWhenUnspecified = true;
            options.ReportApiVersions = true;
        })
        .AddMvc(options => options.Conventions.Add(new ApiVersionsConvention(featuresOptions)))
        .AddApiExplorer(options =>
        {
            // The format for this is 'v'major[.minor][-status] ex. v1.0-prerelease
            options.GroupNameFormat = "'v'VVV";
            options.SubstituteApiVersionInUrl = true;
        });
```

`AddApiVersioning()` now returns `IApiVersioningBuilder` and all extensions hang off of that:

- `IApiVersioningBuilder.AddMvc` add MVC Core support for controllers
- `IApiVersioningBuilder.AddApiExplorer` adds the API Explorer extensions
- `IApiVersioningBuilder.AddOData` adds OData support
- `IApiVersioningBuilder.AddODataApiExplorer` adds OData API Explorer extensions

**Comment by smithago** [comment]
Thank you.

I am still getting the ArgumentNullException

**Comment by smithago** [comment]
Thanks. You are right HttpContext.RequestServices is null for us all the time, it blows up only for the health check request because https://github.com/dotnet/aspnet-api-versioning/blob/main/src/AspNetCore/WebApi/src/Asp.Versioning.Http/ApiVersioningFeature.cs#L35 is null.

Not sure what we are doing to make it null. This request is happening after the webhost is started and the app is ready.

Also, I just noticed during the service registration we already have AddMvc
https://github.com/microsoft/dicom-server/blob/main/src/Microsoft.Health.Dicom.Api/Registration/DicomServerServiceCollectionExtensions.cs#L110

The new one(.AddMvc(options => options.Conventions.Add(new ApiVersionsConvention(featuresOptions)))) does not seem to register the Convention at all. Also need help on how to solve it,

**Comment by commonsensesoftware** [comment]
For the 2nd part, you've misunderstood. `IServiceCollection.AddMvc` does something completely different from `IApiVersioningBuilder.AddMvc`. `AddApiVersioning` only adds the required core components for _Minimal APIs_. In order to support controllers, you need `IApiVersioningBuilder.AddMvc`, which adds additional services and support for _conventions_. If you follow the example I provided above - verbatim, you'll see the difference.

For the 1st part, let me see if I can enlist some help. I know this issue is external and related to `IHttpContextAccessor`, but I'm not entirely sure how to guide you toward a solution. I try not to punt issues.

**Comment by commonsensesoftware** [comment]
After quite a bit of searching, I don't see anything related to `HttpContext.RequestServices` ever being `null`. While it is possible to assign the property to `null` that is very strange and highly unlikely. Looking at the source, this property is **never** `null`, _except_ for:

https://github.com/dotnet/aspnetcore/blob/2745e0b1e0b8bdfe428d8d115cae0d0f42bcea7b/src/Http/Http/src/DefaultHttpContext.cs#L88

This suggests to me that `ITelemetryInitializer.Initialize` is happening after `DefaultHttpContext.Uninitialize` has been called. I can also see that this only happens when the `DefaultHttpContextFactory` is disposed:

https://github.com/dotnet/aspnetcore/blob/2745e0b1e0b8bdfe428d8d115cae0d0f42bcea7b/src/Hosting/Hosting/src/Http/DefaultHttpContextFactory.cs#L88

This would likely happen when the scoped `IServiceProvider` for the request has been disposed. I know very little about this code or how Application Insights is being used, but it looks to me like it's happening after the request has been torn down. If you're able to debug and watch the value, I suspect you can see that `DefaultHttpContext._active` is `false`, which would confirm my suspicion that it has been _uninitialized_, but it hasn't been GC'd - yet.

@davidfowl do you have any additional thoughts or suggestions here?

**Comment by davidfowl** [comment]
Ohh my favorite issue https://github.com/dotnet/aspnetcore/issues/42040

**Comment by commonsensesoftware** [comment]
@davidfowl thanks for taking the time to confirm. That issue seems to be inline with the behavior described. The issue referenced seems to suggest an exception should be thrown when you do something _wrong_. Will that actually _fix_ the issue? Is there a possible workaround for @smithago, no matter how ugly? I imagine that involves some type of horrible locking strategy, but that may be the only option to get unblocked in the short term.

**Comment by commonsensesoftware** [comment]
I believe this is happening due to what I mentioned above. I noticed that although all of your controllers inherit from `ControllerBase`, you are not applying `ApiControllerAttribute` which applies the _API Behaviors_. This is not a requirement and you may well have a perfectly valid reason for doing that, but it is resulting in **all** of your controllers being _filtered_ out from API versioning. Subsequently, that means your convention never runs because no controllers are ever processed.

There are multiple options available.

1. Apply `[ApiController]` to your API controllers

2. If all controllers will always be API controllers, you can use:

`[assembly: Microsoft.AspNetCore.Mvc.ApiController]`

or you can put it into your `*.csproj`, `Directory.Build.props` or `Directory.Build.targets` a la:

```xml
<ItemGroup>
 <AssemblyAttribute Include="Microsoft.AspNetCore.Mvc.ApiControllerAttribute" />
</ItemGroup>
```

When the attribute is applied to the assembly, all controllers are marked as API controllers.

3. You can replace the default `IApiControllerFilter` with:

```c#
services.Replace(ServiceDescriptor.Transient<IApiControllerFilter, NoControllerFilter>());
```

This would not filter anything and is equivalent to the old `ApiVersioningOptions.UseApiBehavior = false` configuration option. That appears to cover your scenario, but if you need something more, you can create a custom `IApiControllerFilter` or just add a custom `IApiControllerSpecification`. For example:

```c#
internal sealed class ControllerBaseSpecification : IApiControllerSpecification
{
    public bool IsSatisfiedBy(ControllerModel controller) =>
        typeof(ControllerBase).Equals(controller.ControllerType.BaseType);
}
```

indicates that any controller that inherits from `ControllerBase` is an _API Controller_ (which is only true if your app says it is). You would then register it with:

```c#
services.TryAddEnumerable(ServiceDescriptor.Transient<IApiControllerSpecification, ControllerBaseSpecification>());
```

That's a lot of options with pros and cons. You'll have to choose the one that makes the most sense for you.

**Comment by smithago** [comment]
Thanks, we only use APIControllers, I went with option#3. 

I can see the versions are now applied to the controller in the convention. But I see versions are not getting enforced. I call /v3/... and it continues to work. Before it would throw UnsupportedApiVersion

**Comment by commonsensesoftware** [comment]
@smithago Following up to see if there was any additional progress or questions. Happy to help you drive this to conclusion. It would seem you're pretty close.

**Comment by commonsensesoftware** [comment]
This thread has gone dark. It appears that you solved or found a suitable workaround. If I've missed something, feel free to re-open the issue.
