### ISSUE TITLE
multiple configuration in dot net core 6 versioning with same name controller

### ISSUE THREAD

**Issue by Aksh-kumar** [dotnet/aspnet-api-versioning#993]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am trying to configure versioning with same name controller with different namespace.
I have a separate project for controller say presentation layer which have all the controllers in 2 different name space i.e. v1 and v2

my folder structure look like this

presentation
|
|-----controller
           |
           |
            ------ v1 // Have namespace Presentation.Controllers.v1
                      |
                       -----APIControllerv1Base.cs
                       ---- CountryController.cs
           ------- v2    // have namespace Presentation.Controllers.v2
                       |
                        ----  APIControllerv2Base.cs
                        ---- CountryController.cs 

 
 and My dependency Injection look like 

```
 serviceCollection.AddApiVersioning(x =>
        {
                x.DefaultApiVersion = new ApiVersion(1, 0);
                x.AssumeDefaultVersionWhenUnspecified = true;
                x.ReportApiVersions = true;
                x.ApiVersionReader = ApiVersionReader.Combine(
                new HeaderApiVersionReader("x-api-version"),
                new UrlSegmentApiVersionReader(),
                new MediaTypeApiVersionReader("x-api-version")
                );
        });

        serviceCollection = serviceCollection.AddVersionedApiExplorer(options =>
        {
            options.GroupNameFormat = "'v'VVV";
            options.SubstituteApiVersionInUrl = true;
            // options.AssumeDefaultVersionWhenUnspecified = true;
        });
```

and in program.cs

```
builder.Services.AddEndpointsApiExplorer().
    AddSwaggerGen(o =>
    {
        o.OperationFilter<SwaggerDefaultValues>();
        o.ResolveConflictingActions(apiDescriptions => apiDescriptions.Last());
    }).
    AddTransient<IConfigureOptions<SwaggerGenOptions>, ConfigureSwaggerOptions>().
    AddControllers();

var app = builder.Build();
// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    var apiVersionDescriptionProvider = app.Services.GetRequiredService<IApiVersionDescriptionProvider>();
    app.UseSwagger();
    // app.UseSwaggerWithVersioning();
    app.UseSwaggerUI(options =>
    {
        var descriptions = apiVersionDescriptionProvider.ApiVersionDescriptions.Reverse();
        foreach (var description in descriptions)
        {
            var url = $"/swagger/{description.GroupName}/swagger.json";
            var name = description.GroupName.ToUpperInvariant();
            options.SwaggerEndpoint(url, name);
        }
        // options.RoutePrefix = ""; // swagger UI at the root index.html
    });
```

Now If I run in debug mode my swagger is only showing v1 in the swagger defination dropdown and If I try to hit v1 api it will go to v2 controller

![swagger_api_issue](https://github.com/dotnet/aspnet-api-versioning/assets/21700957/049929a1-d9a2-4e61-a7a4-ebd175134b87)

Refer the zip of sample project.

### Expected Behavior

I should able to see the 1 and v2 in the swagger dropdown.
and v1 and v2 controller should hit as per the url versioning.

### .NET Version

6.0

### Anything else?

[WorldDB.CleanArchitecture.zip](https://github.com/dotnet/aspnet-api-versioning/files/11643261/WorldDB.CleanArchitecture.zip)

**Comment by commonsensesoftware** [comment]
Thank you for the repro. That is immensely useful at tracking down and addressing your issue. There are a litany of issues as to why this is not working as expected.

First and foremost, `5.1.0` does **not** officially support .NET 6. The correct, current packages for .NET 6 are:

- [Asp.Versioning.Mvc (6.4.0)](https://www.nuget.org/packages/Asp.Versioning.Mvc/6.4.0)
- [Asp.Versioning.Mvc.ApiExplorer (6.4.0)](https://www.nuget.org/packages/Asp.Versioning.Mvc.ApiExplorer/6.4.0)

You can consider moving to `7.0.0`, which will support .NET 7, but know that new, major versions are not always backward compatible. You should target the supported version of the package that matches your ASP.NET Core runtime target.

The next problem is that that namespaces and APIs have changed slightly.

- DI is now configured using `IApiVersioningBuilder` with configurations chained; for example, `services.AddApiVersioning().AddMvc().AddApiExplorer()`
- `IApiVersionDescriptionProvider` still exists and is supported, but you should consider the more succinct `app.DescribeApiVersions()` extension method which covers controllers, Minimal APIs, or both

Your configuration is a bit strange. You're combining versioning by URL segment, header, and media type, but that is nonsensical. Technically, you can add all of these together, but once you version by URL segment, every URL must have the API version in it. It doesn't make sense to also require a client to include the API version in a header or media type. In addition, `AssumeDefaultVersionWhenUnspecified = true` will not do what you think it will do when versioning by URL segment. It is not possible to have a default value in the middle of a route template. The same would be true if the route were `order/{id}/items`. The `{id}` route parameter **always** has to be specified. The only way to make it work is to use _Double Route Registration_; for example `[Route("api/[controller]")]`. This feature was **only** meant for backward compatibility. These are just a few of the problems and consequences of versioning by URL segment. If you have choice, I recommend against it. Using a segment of the URL to version is not RESTful as it violates the _Uniform Interface_ constraint.

`ApiVersionAttribute` and its siblings are **not** inherited by design. If they were, then `ControllerV2` would inherit `1.0` and define `2.0`. This will lead to ambiguity for `1.0` between `ControllerV1` and `ControllerV2`. You can use inheritance, but the API versions must be explicitly defined on their corresponding controllers. The benefit of this approach is that you don't need `[MapToApiVersion]` because all actions implicitly map to all API versions declared by their defining controller. If you really want inheritance, you'd have to roll your own custom attributes starting with `ApiVersionsBaseAttribute` or implementing `IApiVersionProvider` directly.

I've taken the liberty of making the necessary changes to your repro and echoing it back for you to review.
[Issue993.zip](https://github.com/dotnet/aspnet-api-versioning/files/11646149/Issue993.zip)

**Comment by commonsensesoftware** [comment]
@Aksh-kumar,

`AddMvc` is part of API Versioning. That adds the MVC Core controller support. Without it, only Minimal APIs would be supported. This is completely difference from `services.AddMvcCore()` which adds the core MVC services or `services.AddMvc()` which adds the full MVC stack. `IApiVersioningBuilder.AddMvc` has no impact on filters.

It's not clear what you mean by:

>After considering all the changes Still swagger is not getting loaded, when application started it just keep loading.

The solution provided above works without modification. Did you make changes to it? I would not provide a solution that doesn't work.

![image](https://github.com/dotnet/aspnet-api-versioning/assets/11765008/abde69db-fbe4-4463-8bb0-a175d325f134)
![image](https://github.com/dotnet/aspnet-api-versioning/assets/11765008/d95a4bf6-36e7-4b02-8b35-9753aba73f72)

**Comment by Aksh-kumar** [comment]
@commonsensesoftware  thanks just uncomment the AddMvc() part it works fine.
